import type { CityInfo } from "@/lib/localSeo";

/* Rajasthan, Haryana, Punjab — real district headquarters not yet covered by
   the hand-authored rajasthanCities / haryanaCities / punjabCities arrays in
   lib/localSeo.ts. One entry, "SAS Nagar" (slug sas-nagar), was deliberately
   dropped from the input list: it is the same real place as the already-live
   "mohali" city page (SAS Nagar is Mohali's official district name), so
   adding it would have been near-duplicate content under a second URL. */
export const group4Cities: CityInfo[] = [
  // ══════════════ RAJASTHAN ══════════════
  { name: "Beawar", slug: "beawar", state: "Rajasthan", type: "growing", tagline: "a historic cloth-and-wool trading town split from Ajmer district", context: "the wool and khadi processing units, cotton ginning mills, and local wholesale trade", nearby: ["ajmer", "bhilwara", "pali", "jaipur"] },
  { name: "Didwana-Kuchaman", slug: "didwana-kuchaman", state: "Rajasthan", type: "district", tagline: "a salt-lake and marble-quarrying district headquarters on the Shekhawati-Marwar border", context: "the salt production units, marble and stone quarrying, and agricultural trade", nearby: ["nagaur", "sikar", "jaipur", "ajmer"] },
  { name: "Nagaur", slug: "nagaur", state: "Rajasthan", type: "headquarters", tagline: "an agricultural and livestock-trading hub famous for its Nagauri cattle breed", context: "the livestock and cattle-fair trade, handicraft and namda units, and agro-processing businesses", nearby: ["jodhpur", "bikaner", "didwana-kuchaman", "ajmer"] },
  { name: "Tonk", slug: "tonk", state: "Rajasthan", type: "district", tagline: "a Nawabi heritage town and agricultural trade center south of Jaipur", context: "the hand-block textile printing units, oilseed and grain trade, and local retail", nearby: ["jaipur", "ajmer", "bhilwara", "kota"] },
  { name: "Bharatpur", slug: "bharatpur", state: "Rajasthan", type: "headquarters", tagline: "the Keoladeo bird-sanctuary city and eastern gateway of Rajasthan on the Agra border", context: "the wildlife-tourism trade, mustard and agricultural markets, and stone-craft businesses", nearby: ["dholpur", "karauli", "alwar", "jaipur"] },
  { name: "Deeg", slug: "deeg", state: "Rajasthan", type: "district", tagline: "a heritage palace-and-water-garden town split from Bharatpur district", context: "the heritage tourism trade, agricultural markets, and local retail", nearby: ["bharatpur", "karauli", "dholpur", "alwar"] },
  { name: "Dholpur", slug: "dholpur", state: "Rajasthan", type: "district", tagline: "a red-sandstone quarrying district headquarters on the Chambal ravines", context: "the sandstone quarrying and stone-cutting units, agricultural trade, and local markets", nearby: ["bharatpur", "karauli", "agra", "gwalior"] },
  { name: "Karauli", slug: "karauli", state: "Rajasthan", type: "district", tagline: "a red-stone quarrying district headquarters and pilgrimage town of the Kaila Devi temple", context: "the stone quarrying and carving units, pilgrimage tourism, and agricultural trade", nearby: ["sawai-madhopur", "dholpur", "bharatpur", "jaipur"] },
  { name: "Sawai Madhopur", slug: "sawai-madhopur", state: "Rajasthan", type: "headquarters", tagline: "the gateway town to Ranthambore National Park, one of India's premier tiger reserves", context: "the wildlife-tourism and safari trade, hospitality businesses, and agricultural markets", nearby: ["karauli", "kota", "tonk", "jaipur"] },
  { name: "Churu", slug: "churu", state: "Rajasthan", type: "district", tagline: "a Shekhawati desert town famed for its painted merchant havelis", context: "the heritage-tourism trade, handicraft businesses, and agricultural markets", nearby: ["sikar", "jhunjhunu", "bikaner", "jaipur"] },
  { name: "Hanumangarh", slug: "hanumangarh", state: "Rajasthan", type: "headquarters", tagline: "a canal-irrigated grain-belt district headquarters of northern Rajasthan", context: "the wheat and cotton trade, agricultural equipment dealers, and mandi businesses", nearby: ["sri-ganganagar", "churu", "bikaner", "sirsa"] },
  { name: "Sri Ganganagar", slug: "sri-ganganagar", state: "Rajasthan", type: "headquarters", tagline: "the food bowl of Rajasthan, built on the Gang Canal irrigation system", context: "the wheat and kinnow-citrus trade, cotton ginning mills, and agricultural markets", nearby: ["hanumangarh", "bikaner", "fazilka", "churu"] },
  { name: "Dausa", slug: "dausa", state: "Rajasthan", type: "growing", tagline: "a fast-growing district on the Jaipur-Agra corridor with a strong remittance economy", context: "the agricultural trade, remittance-funded retail, and transport and logistics businesses", nearby: ["jaipur", "alwar", "sawai-madhopur", "bharatpur"] },
  { name: "Jhunjhunu", slug: "jhunjhunu", state: "Rajasthan", type: "headquarters", tagline: "a Shekhawati heritage town and the ancestral home of many prominent Marwari business families", context: "the heritage and haveli tourism, remittance-funded retail, and agricultural trade", nearby: ["sikar", "churu", "alwar", "jaipur"] },
  { name: "Khairthal-Tijara", slug: "khairthal-tijara", state: "Rajasthan", type: "district", tagline: "an NCR-adjacent industrial district carved from Alwar, anchored by the Bhiwadi manufacturing belt", context: "the manufacturing and auto-ancillary units, warehousing, and agricultural trade", nearby: ["alwar", "jaipur", "gurugram", "dausa"] },
  { name: "Kotputli-Behror", slug: "kotputli-behror", state: "Rajasthan", type: "district", tagline: "an industrial gateway district on the Delhi-Jaipur highway, near the Neemrana investment corridor", context: "the manufacturing and industrial estates, logistics and warehousing, and agricultural trade", nearby: ["alwar", "jaipur", "khairthal-tijara", "gurugram"] },
  { name: "Sikar", slug: "sikar", state: "Rajasthan", type: "headquarters", tagline: "a Shekhawati education and coaching hub, and one of India's largest sources of army recruits", context: "the coaching-institute ecosystem, remittance-funded retail, and agricultural trade", nearby: ["jhunjhunu", "churu", "jaipur", "nagaur"] },
  { name: "Balotra", slug: "balotra", state: "Rajasthan", type: "growing", tagline: "a textile dyeing-and-printing industrial town split from Barmer district", context: "the textile dyeing and printing units, handicraft export businesses, and agricultural trade", nearby: ["barmer", "jalore", "pali", "jodhpur"] },
  { name: "Barmer", slug: "barmer", state: "Rajasthan", type: "headquarters", tagline: "a desert-belt district headquarters known for its oil-and-gas fields and handicraft exports", context: "the oil-and-gas ancillary services, handicraft and embroidery export units, and agricultural trade", nearby: ["jaisalmer", "jalore", "balotra", "jodhpur"] },
  { name: "Jaisalmer", slug: "jaisalmer", state: "Rajasthan", type: "headquarters", tagline: "the Golden City of the Thar Desert and a major international tourism destination", context: "the desert-safari and heritage tourism trade, handicraft businesses, and hospitality services", nearby: ["barmer", "jodhpur", "bikaner", "jaipur"] },
  { name: "Jalore", slug: "jalore", state: "Rajasthan", type: "growing", tagline: "the granite city of India, with a large stone-quarrying and export industry", context: "the granite quarrying and polishing units, export trading houses, and agricultural trade", nearby: ["barmer", "pali", "sirohi", "jodhpur"] },
  { name: "Pali", slug: "pali", state: "Rajasthan", type: "headquarters", tagline: "a textile dyeing-and-printing export hub known as Rajasthan's Sun City", context: "the textile processing and export units, dyeing-and-printing clusters, and agricultural trade", nearby: ["jodhpur", "sirohi", "jalore", "ajmer"] },
  { name: "Phalodi", slug: "phalodi", state: "Rajasthan", type: "district", tagline: "a salt-production town in the Thar Desert, split from Jodhpur district", context: "the salt manufacturing units, agricultural markets, and local trade", nearby: ["jodhpur", "bikaner", "jaisalmer", "nagaur"] },
  { name: "Sirohi", slug: "sirohi", state: "Rajasthan", type: "growing", tagline: "home to Mount Abu, Rajasthan's only hill station, and a marble-trading district", context: "the hill-station tourism trade, marble and granite units, and agricultural markets", nearby: ["pali", "jalore", "udaipur", "jodhpur"] },
  { name: "Baran", slug: "baran", state: "Rajasthan", type: "district", tagline: "a major coriander and grain-trading agricultural district headquarters", context: "the spice (coriander) trade, grain mandis, and agricultural processing businesses", nearby: ["kota", "jhalawar", "bundi", "sawai-madhopur"] },
  { name: "Bundi", slug: "bundi", state: "Rajasthan", type: "growing", tagline: "a heritage town famed for its stepwells and Bundi school of miniature painting", context: "the heritage tourism trade, handicraft businesses, and agricultural markets", nearby: ["kota", "chittorgarh", "jhalawar", "ajmer"] },
  { name: "Jhalawar", slug: "jhalawar", state: "Rajasthan", type: "district", tagline: "a citrus and soyabean farming district headquarters in the Hadoti region", context: "the orange and citrus trade, agricultural processing units, and local markets", nearby: ["kota", "baran", "chittorgarh", "bundi"] },
  { name: "Banswara", slug: "banswara", state: "Rajasthan", type: "district", tagline: "a tribal-majority district known as the city of a hundred islands for its many reservoirs", context: "the mineral (soapstone) mining, tribal cooperative businesses, and agricultural trade", nearby: ["dungarpur", "chittorgarh", "udaipur", "pratapgarh-rajasthan"] },
  { name: "Chittorgarh", slug: "chittorgarh", state: "Rajasthan", type: "headquarters", tagline: "the historic fort city of Rajasthan, now also a cement and zinc-mining industrial hub", context: "the cement manufacturing units, zinc and mineral mining ancillary trade, and heritage tourism", nearby: ["udaipur", "bhilwara", "kota", "rajsamand"] },
  { name: "Dungarpur", slug: "dungarpur", state: "Rajasthan", type: "district", tagline: "a tribal-belt district headquarters in southern Rajasthan known as the City of Hills", context: "the marble and mineral trade, tribal cooperative businesses, and agricultural markets", nearby: ["banswara", "udaipur", "pratapgarh-rajasthan", "sirohi"] },
  { name: "Pratapgarh Rajasthan", slug: "pratapgarh-rajasthan", state: "Rajasthan", type: "district", tagline: "the home of Thewa — a centuries-old gold-on-glass jewellery art found nowhere else in India", context: "the Thewa jewellery artisan workshops, agricultural trade, and tribal cooperative businesses", nearby: ["chittorgarh", "udaipur", "banswara", "dungarpur"] },
  { name: "Rajsamand", slug: "rajsamand", state: "Rajasthan", type: "growing", tagline: "the marble capital of Rajasthan, with one of India's largest marble-processing clusters", context: "the marble mining and processing units, stone-export trading houses, and tourism", nearby: ["udaipur", "chittorgarh", "ajmer", "pali"] },
  { name: "Salumbar", slug: "salumbar", state: "Rajasthan", type: "district", tagline: "a tribal-belt district headquarters carved from Udaipur in southern Rajasthan", context: "the agricultural trade, tribal cooperative businesses, and local retail markets", nearby: ["udaipur", "chittorgarh", "dungarpur", "rajsamand"] },

  // ══════════════ HARYANA ══════════════
  { name: "Kaithal", slug: "kaithal", state: "Haryana", type: "district", tagline: "an agricultural district headquarters linked to Mahabharata legend, with active grain markets", context: "the grain and paddy trade, straw-board and paper mills, and agricultural equipment dealers", nearby: ["kurukshetra", "jind", "karnal", "panipat"] },
  { name: "Panchkula", slug: "panchkula", state: "Haryana", type: "growing", tagline: "a planned city in the Chandigarh tricity, with a fast-growing IT and real-estate economy", context: "the IT and corporate offices, real-estate development, and retail businesses", nearby: ["chandigarh", "mohali", "ambala", "yamunanagar"] },
  { name: "Jhajjar", slug: "jhajjar", state: "Haryana", type: "growing", tagline: "an NCR-adjacent industrial district anchored by the Bahadurgarh manufacturing belt", context: "the manufacturing and industrial estates, thermal-power ancillary units, and warehousing", nearby: ["rohtak", "delhi", "gurugram", "sonipat"] },
  { name: "Bhiwani", slug: "bhiwani", state: "Haryana", type: "headquarters", tagline: "known as 'Mini Cuba' for producing many of India's Olympic boxers, and a cotton-trading hub", context: "the cotton ginning and oilseed mills, sports-training academies, and agricultural trade", nearby: ["rohtak", "hisar", "charkhi-dadri", "jind"] },
  { name: "Charkhi Dadri", slug: "charkhi-dadri", state: "Haryana", type: "district", tagline: "an agricultural district headquarters carved from Bhiwani in south-western Haryana", context: "the grain and cotton trade, agricultural equipment dealers, and local markets", nearby: ["bhiwani", "rohtak", "hisar", "jhajjar"] },
  { name: "Hansi", slug: "hansi", state: "Haryana", type: "district", tagline: "a historic town near Hisar known for its ancient fort and handloom weaving tradition", context: "the handloom weaving units, agricultural trade, and local markets", nearby: ["hisar", "bhiwani", "jind", "rohtak"] },
  { name: "Fatehabad", slug: "fatehabad", state: "Haryana", type: "district", tagline: "a cotton-belt agricultural district headquarters of western Haryana", context: "the cotton ginning mills, grain trade, and agricultural equipment dealers", nearby: ["hisar", "sirsa", "jind", "kaithal"] },
  { name: "Sirsa", slug: "sirsa", state: "Haryana", type: "headquarters", tagline: "a cotton and grain mandi town on Haryana's border with Punjab and Rajasthan", context: "the cotton and grain trade, agricultural markets, and cross-border logistics", nearby: ["fatehabad", "hisar", "hanumangarh", "sri-ganganagar"] },
  { name: "Jind", slug: "jind", state: "Haryana", type: "district", tagline: "an agricultural district headquarters known for its grain markets and wrestling academies", context: "the grain trade, sports-training academies, and agricultural equipment dealers", nearby: ["kaithal", "hisar", "rohtak", "karnal"] },
  { name: "Rewari", slug: "rewari", state: "Haryana", type: "growing", tagline: "a traditional brassware-manufacturing town and NCR-adjacent industrial belt", context: "the brass utensil manufacturing units, auto-ancillary industrial estates, and trade", nearby: ["gurugram", "mahendragarh", "jhajjar", "alwar"] },
  { name: "Mahendragarh", slug: "mahendragarh", state: "Haryana", type: "district", tagline: "an agricultural district headquarters on the Rajasthan border with a strong remittance economy", context: "the agricultural trade, remittance-funded retail, and local markets", nearby: ["rewari", "bhiwani", "alwar", "jhajjar"] },
  { name: "Nuh", slug: "nuh", state: "Haryana", type: "district", tagline: "the district headquarters of the Mewat region, with a developing agricultural and retail economy", context: "the agricultural markets, retail businesses, and local service providers", nearby: ["gurugram", "palwal", "alwar", "rewari"] },
  { name: "Palwal", slug: "palwal", state: "Haryana", type: "growing", tagline: "an NCR-adjacent district headquarters on the Kundli-Manesar-Palwal expressway corridor", context: "the warehousing and logistics parks, manufacturing units, and agricultural trade", nearby: ["faridabad", "gurugram", "nuh", "mathura"] },

  // ══════════════ PUNJAB ══════════════
  { name: "Faridkot", slug: "faridkot", state: "Punjab", type: "district", tagline: "a former princely-state town and agricultural mandi headquarters of the Malwa region", context: "the grain and cotton trade, agricultural markets, and local retail", nearby: ["muktsar", "moga", "ludhiana", "bathinda"] },
  { name: "Mansa", slug: "mansa", state: "Punjab", type: "district", tagline: "a cotton-belt agricultural district headquarters in the Malwa region", context: "the cotton ginning mills, grain trade, and agricultural equipment dealers", nearby: ["bathinda", "sangrur", "muktsar", "barnala"] },
  { name: "Muktsar", slug: "muktsar", state: "Punjab", type: "district", tagline: "a historic Sikh pilgrimage town and cotton-trading hub of the Malwa belt", context: "the pilgrimage tourism, cotton and grain trade, and agricultural markets", nearby: ["faridkot", "fazilka", "bathinda", "mansa"] },
  { name: "Firozpur", slug: "firozpur", state: "Punjab", type: "headquarters", tagline: "a border cantonment town on the India-Pakistan frontier with an agrarian economy", context: "the cantonment economy, grain trade, and agricultural markets", nearby: ["fazilka", "faridkot", "moga", "amritsar"] },
  { name: "Fazilka", slug: "fazilka", state: "Punjab", type: "district", tagline: "a cotton-belt border district headquarters split from Firozpur", context: "the cotton ginning mills, grain trade, and cross-border logistics", nearby: ["firozpur", "muktsar", "sri-ganganagar", "hanumangarh"] },
  { name: "Moga", slug: "moga", state: "Punjab", type: "headquarters", tagline: "an agricultural and dairy-processing hub of the Malwa region, home to major food-processing plants", context: "the dairy and food-processing units, grain trade, and agricultural markets", nearby: ["ludhiana", "faridkot", "firozpur", "barnala"] },
  { name: "Hoshiarpur", slug: "hoshiarpur", state: "Punjab", type: "headquarters", tagline: "a Doaba-region town famed for its wood-inlay furniture craft and NRI remittance economy", context: "the wood-inlay furniture units, remittance-funded retail, and agricultural trade", nearby: ["jalandhar", "kapurthala", "shaheed-bhagat-singh-nagar", "gurdaspur"] },
  { name: "Kapurthala", slug: "kapurthala", state: "Punjab", type: "headquarters", tagline: "a former princely-state town, home to one of India's major rail coach manufacturing factories", context: "the railway ancillary manufacturing units, heritage tourism, and agricultural trade", nearby: ["jalandhar", "hoshiarpur", "amritsar", "ludhiana"] },
  { name: "Shaheed Bhagat Singh Nagar", slug: "shaheed-bhagat-singh-nagar", state: "Punjab", type: "district", tagline: "a Doaba-region district headquarters named for Shaheed Bhagat Singh, with a strong NRI remittance economy", context: "the remittance-funded retail, agricultural trade, and local markets", nearby: ["jalandhar", "hoshiarpur", "ludhiana", "kapurthala"] },
  { name: "Tarn Taran", slug: "tarn-taran", state: "Punjab", type: "district", tagline: "a Sikh pilgrimage town around the Tarn Taran Sahib gurdwara, near the Pakistan border", context: "the pilgrimage tourism, agricultural trade, and border-area logistics", nearby: ["amritsar", "firozpur", "gurdaspur", "kapurthala"] },
  { name: "Sangrur", slug: "sangrur", state: "Punjab", type: "headquarters", tagline: "a major grain-mandi town at the heart of Punjab's Malwa agricultural belt", context: "the grain and cotton trade, agricultural equipment dealers, and food-processing units", nearby: ["barnala", "patiala", "malerkotla", "bathinda"] },
  { name: "Malerkotla", slug: "malerkotla", state: "Punjab", type: "district", tagline: "Punjab's only Muslim-majority town, historically known for its scissors and embroidery craft", context: "the handicraft and embroidery units, hosiery trade, and agricultural markets", nearby: ["sangrur", "ludhiana", "patiala", "barnala"] },
  { name: "Fatehgarh Sahib", slug: "fatehgarh-sahib", state: "Punjab", type: "headquarters", tagline: "home to the Mandi Gobindgarh steel-rolling-mill cluster, known as Punjab's Steel Town", context: "the steel re-rolling mills, scrap-metal trade, and heritage tourism", nearby: ["ludhiana", "patiala", "sangrur", "chandigarh"] },
  { name: "Barnala", slug: "barnala", state: "Punjab", type: "district", tagline: "an agricultural mandi district headquarters in the cotton-and-grain belt of Malwa", context: "the cotton ginning mills, grain trade, and agricultural markets", nearby: ["sangrur", "bathinda", "moga", "malerkotla"] },
  { name: "Rupnagar", slug: "rupnagar", state: "Punjab", type: "growing", tagline: "an education and engineering hub on the Sutlej, home to IIT Ropar", context: "the education institutions, engineering ancillary units, and agricultural trade", nearby: ["chandigarh", "mohali", "fatehgarh-sahib", "ludhiana"] },
  { name: "Gurdaspur", slug: "gurdaspur", state: "Punjab", type: "district", tagline: "a border-belt district headquarters in Punjab's sports-goods and agricultural corridor", context: "the sports-goods ancillary units, agricultural trade, and cross-border logistics", nearby: ["pathankot", "amritsar", "hoshiarpur", "jalandhar"] },
  { name: "Pathankot", slug: "pathankot", state: "Punjab", type: "growing", tagline: "the gateway town to Jammu & Kashmir and Himachal Pradesh, with a cantonment and timber-trade economy", context: "the timber and plywood trade, cantonment economy, and tourism-transit businesses", nearby: ["gurdaspur", "jammu", "dharamshala", "amritsar"] },
];
