import type { CityInfo } from "@/lib/localSeo";

export const group2Cities: CityInfo[] = [
  /* ══════════════════════════════════════════════
     WEST BENGAL
  ══════════════════════════════════════════════ */
  { name: "North 24 Parganas", slug: "north-24-parganas", state: "West Bengal", type: "headquarters", tagline: "the jute-mill and industrial belt immediately north of Kolkata, centred on Barasat and Barrackpore", context: "the Hooghly-bank jute and engineering mills, Barasat's wholesale trade, and Kolkata-commuter retail", nearby: ["kolkata", "howrah", "hooghly", "nadia"] },
  { name: "South 24 Parganas", slug: "south-24-parganas", state: "West Bengal", type: "headquarters", tagline: "West Bengal's largest district, spanning Kolkata's southern suburbs down to the Sundarbans delta", context: "the Sundarbans fisheries and eco-tourism trade, Diamond Harbour's port and agri markets, and Kolkata-linked retail", nearby: ["kolkata", "howrah", "north-24-parganas", "hooghly"] },
  { name: "Hooghly", slug: "hooghly", state: "West Bengal", type: "headquarters", tagline: "a Hooghly-river industrial belt of former colonial trading towns, from Chinsurah to Serampore", context: "the jute and textile mills, Serampore's college and print heritage, and river-port trade", nearby: ["kolkata", "howrah", "north-24-parganas", "bardhaman"] },
  { name: "Nadia", slug: "nadia", state: "West Bengal", type: "headquarters", tagline: "a Hooghly-river district of Vaishnav pilgrimage and planned towns, anchored by Nabadwip and Kalyani", context: "the Nabadwip pilgrimage and sweets trade, Kalyani's university and planned-township economy, and Ranaghat's textile and jute trade", nearby: ["krishnanagar", "kolkata", "north-24-parganas", "hooghly"] },
  { name: "Bankura", slug: "bankura", state: "West Bengal", type: "headquarters", tagline: "the terracotta-temple and Bankura-horse handicraft district of the dry Rarh plateau", context: "the terracotta and Bankura-horse artisan clusters, rice and pulses trade, and forest-fringe tourism", nearby: ["purulia", "bardhaman", "birbhum", "kolkata"] },
  { name: "Purulia", slug: "purulia", state: "West Bengal", type: "district", tagline: "a mineral-rich plateau district on the Jharkhand border, home of the Chhau mask-dance tradition", context: "the stone and mineral trade, Chhau craft and tourism, and agricultural markets", nearby: ["bankura", "bardhaman", "dhanbad", "ranchi"] },
  { name: "Paschim Medinipur", slug: "paschim-medinipur", state: "West Bengal", type: "headquarters", tagline: "the erstwhile Midnapore district's western half, anchored by its historic namesake town on the Kangsabati", context: "the Midnapore town's administrative and education economy, sal-forest and handicraft trade, and agricultural markets", nearby: ["kharagpur", "kolkata", "bankura", "purulia"] },
  { name: "Purba Medinipur", slug: "purba-medinipur", state: "West Bengal", type: "growing", tagline: "the coastal half of old Medinipur, home to Haldia's port-petrochemical complex and Digha's beach-tourism economy", context: "the Haldia port and petrochemical ancillary trade, Digha's beach-tourism and hospitality sector, and Tamluk's agricultural markets", nearby: ["kolkata", "howrah", "paschim-medinipur", "kharagpur"] },
  { name: "Jhargram", slug: "jhargram", state: "West Bengal", type: "district", tagline: "a forested tribal-belt district carved out of Medinipur, known for its Jhargram Raj palace and sal forests", context: "the forest-produce and tribal handicraft trade, agricultural markets, and wildlife-corridor tourism", nearby: ["paschim-medinipur", "purulia", "bankura", "kolkata"] },
  { name: "Murshidabad", slug: "murshidabad", state: "West Bengal", type: "headquarters", tagline: "the historic seat of the Bengal Nawabs, centred on Murshidabad town's Hazarduari Palace and silk-weaving heritage", context: "the silk weaving and ivory-craft artisans, mango orchards, and heritage tourism around Hazarduari", nearby: ["baharampur", "malda", "kolkata", "bardhaman"] },
  { name: "Uttar Dinajpur", slug: "uttar-dinajpur", state: "West Bengal", type: "district", tagline: "a North Bengal district headquartered at Raiganj on the jute-and-rice belt of the Dinajpur plains", context: "the jute and paddy trade, Kulik bird-sanctuary tourism, and local wholesale markets", nearby: ["malda", "dakshin-dinajpur", "siliguri", "cooch-behar"] },
  { name: "Dakshin Dinajpur", slug: "dakshin-dinajpur", state: "West Bengal", type: "district", tagline: "a Bangladesh-border district headquartered at Balurghat with an agrarian rice-and-jute economy", context: "the paddy and jute trade, border-town wholesale markets, and agricultural processing", nearby: ["uttar-dinajpur", "malda", "siliguri", "cooch-behar"] },
  { name: "Jalpaiguri", slug: "jalpaiguri", state: "West Bengal", type: "headquarters", tagline: "the Dooars tea-garden district of North Bengal, gateway to the Gorumara and Jaldapara forests", context: "the tea-estate economy, timber and forest-fringe trade, and wildlife-tourism operators", nearby: ["siliguri", "alipurduar", "cooch-behar", "darjeeling"] },
  { name: "Alipurduar", slug: "alipurduar", state: "West Bengal", type: "growing", tagline: "a Dooars tea-and-railway-junction district bordering Bhutan and Assam", context: "the tea-garden economy, cross-border trade with Bhutan, and railway ancillary businesses", nearby: ["jalpaiguri", "siliguri", "cooch-behar", "darjeeling"] },
  { name: "Cooch Behar", slug: "cooch-behar", state: "West Bengal", type: "headquarters", tagline: "a former princely-state capital in North Bengal known for the Cooch Behar Palace and its rice-and-jute economy", context: "the paddy and jute trade, heritage tourism around the royal palace, and local wholesale markets", nearby: ["jalpaiguri", "alipurduar", "siliguri", "uttar-dinajpur"] },
  { name: "Darjeeling", slug: "darjeeling", state: "West Bengal", type: "major", tagline: "the world-famous Himalayan tea-and-tourism hill station of North Bengal", context: "the tea-estate export trade, hill tourism and hospitality, and handicraft businesses", nearby: ["siliguri", "kalimpong", "jalpaiguri", "gangtok"] },
  { name: "Kalimpong", slug: "kalimpong", state: "West Bengal", type: "growing", tagline: "a Himalayan hill district carved from Darjeeling, known for its flower nurseries and historic Tibet trade route", context: "the floriculture and nursery export trade, hill tourism, and handicraft businesses", nearby: ["darjeeling", "siliguri", "gangtok", "jalpaiguri"] },
  { name: "Birbhum", slug: "birbhum", state: "West Bengal", type: "headquarters", tagline: "the red-soil Rarh district home to Tagore's Shantiniketan and the Kenduli Baul festival", context: "the Visva-Bharati university economy, handloom and terracotta artisan clusters, and heritage tourism", nearby: ["bardhaman", "bankura", "malda", "kolkata"] },

  /* ══════════════════════════════════════════════
     ODISHA
  ══════════════════════════════════════════════ */
  { name: "Khordha", slug: "khordha", state: "Odisha", type: "headquarters", tagline: "the historic old capital of Odisha, now the district anchoring Bhubaneswar's southern industrial belt", context: "the Khordha town administrative and trade economy, the Barunei hill pilgrimage site, and agro-processing units", nearby: ["bhubaneswar", "puri", "cuttack", "nayagarh"] },
  { name: "Jagatsinghpur", slug: "jagatsinghpur", state: "Odisha", type: "growing", tagline: "a coastal district anchoring Paradip, one of India's major all-weather ports", context: "the Paradip port and petrochemical ancillary trade, paddy agriculture, and fisheries", nearby: ["cuttack", "bhubaneswar", "kendrapara", "puri"] },
  { name: "Kendrapara", slug: "kendrapara", state: "Odisha", type: "district", tagline: "a delta district home to the Bhitarkanika mangrove and crocodile sanctuary", context: "the paddy and fisheries economy, Bhitarkanika eco-tourism, and coastal agri-trade", nearby: ["jagatsinghpur", "cuttack", "bhadrak", "jajpur"] },
  { name: "Jajpur", slug: "jajpur", state: "Odisha", type: "growing", tagline: "a Buddhist-heritage district now anchoring the Kalinganagar steel-industrial belt", context: "the Kalinganagar steel and ancillary industries, Biraja temple pilgrimage, and agricultural markets", nearby: ["bhadrak", "kendrapara", "cuttack", "bhubaneswar"] },
  { name: "Bhadrak", slug: "bhadrak", state: "Odisha", type: "headquarters", tagline: "a temple town and agricultural trade hub near the Dhamra port on Odisha's northern coast", context: "the paddy and pulses trade, Bhadrakali temple pilgrimage, and Dhamra port ancillary trade", nearby: ["jajpur", "balasore", "kendrapara", "cuttack"] },
  { name: "Balasore", slug: "balasore", state: "Odisha", type: "headquarters", tagline: "a coastal district known for Chandipur's vanishing beach and the DRDO missile-testing range", context: "the defence-research ancillary economy, fisheries and paddy trade, and coastal tourism", nearby: ["bhadrak", "jajpur", "mayurbhanj", "kolkata"] },
  { name: "Mayurbhanj", slug: "mayurbhanj", state: "Odisha", type: "district", tagline: "a forested former princely state home to the Similipal tiger reserve", context: "the forest-produce and tribal handicraft trade, Similipal wildlife tourism, and agricultural markets", nearby: ["balasore", "kendujhar", "jharsuguda", "jamshedpur"] },
  { name: "Kendujhar", slug: "kendujhar", state: "Odisha", type: "growing", tagline: "a mineral-rich plateau district and one of India's major iron-ore mining belts", context: "the iron-ore mining and ancillary trade, forest-produce economy, and agricultural markets", nearby: ["mayurbhanj", "sundargarh", "jajpur", "rourkela"] },
  { name: "Sundargarh", slug: "sundargarh", state: "Odisha", type: "growing", tagline: "a mineral-rich district anchoring the Rourkela steel-plant region, with its own tribal-majority headquarters town", context: "the iron and manganese ore trade, forest-produce economy, and agricultural markets", nearby: ["rourkela", "kendujhar", "jharsuguda", "mayurbhanj"] },
  { name: "Jharsuguda", slug: "jharsuguda", state: "Odisha", type: "growing", tagline: "an industrial power-and-aluminium hub often called the power capital of Odisha", context: "the aluminium smelting and thermal-power ancillary industries, coal trade, and local retail", nearby: ["sambalpur", "sundargarh", "bargarh", "rourkela"] },
  { name: "Bargarh", slug: "bargarh", state: "Odisha", type: "district", tagline: "a paddy-rich district of the Hirakud command area, part of western Odisha's rice bowl", context: "the paddy milling and rice trade, Hirakud-irrigated agriculture, and local wholesale markets", nearby: ["sambalpur", "jharsuguda", "subarnapur", "balangir"] },
  { name: "Subarnapur", slug: "subarnapur", state: "Odisha", type: "district", tagline: "a Mahanadi-bank district famed for its Sonepuri ikat handloom sarees", context: "the ikat-weaving handloom clusters, agricultural trade, and river-confluence pilgrimage tourism", nearby: ["balangir", "bargarh", "boudh", "sambalpur"] },
  { name: "Balangir", slug: "balangir", state: "Odisha", type: "headquarters", tagline: "a western-Odisha district headquarters in the KBK belt, historically known for drought resilience programs", context: "the cotton and oilseed trade, agricultural development networks, and local wholesale markets", nearby: ["subarnapur", "kalahandi", "nuapada", "bargarh"] },
  { name: "Nuapada", slug: "nuapada", state: "Odisha", type: "district", tagline: "a border district in Odisha's western KBK belt, adjoining Chhattisgarh", context: "the agricultural and forest-produce trade, cross-border markets with Chhattisgarh, and local retail", nearby: ["balangir", "kalahandi", "raipur", "bargarh"] },
  { name: "Kalahandi", slug: "kalahandi", state: "Odisha", type: "headquarters", tagline: "a KBK-belt district widely cited for its turnaround in paddy productivity, the so-called Kalahandi model", context: "the paddy and horticulture trade, agricultural cooperative networks, and local wholesale markets", nearby: ["nuapada", "balangir", "rayagada", "koraput"] },
  { name: "Rayagada", slug: "rayagada", state: "Odisha", type: "district", tagline: "a tribal-majority Eastern Ghats district known for its weekly Kondh hill markets", context: "the tribal handicraft and produce trade, textile-mill economy, and agricultural markets", nearby: ["koraput", "kalahandi", "gajapati", "srikakulam"] },
  { name: "Nabarangpur", slug: "nabarangpur", state: "Odisha", type: "district", tagline: "a tribal-majority district on the Chhattisgarh-Andhra border with a cotton-and-maize agrarian economy", context: "the cotton and maize trade, tribal cooperative businesses, and local wholesale markets", nearby: ["koraput", "kalahandi", "rayagada", "jagdalpur"] },
  { name: "Koraput", slug: "koraput", state: "Odisha", type: "headquarters", tagline: "an Eastern Ghats district known for NALCO's bauxite-aluminium complex and its hill-grown coffee", context: "the bauxite-aluminium ancillary industries, tribal handicraft trade, and coffee and horticulture", nearby: ["rayagada", "nabarangpur", "malkangiri", "jagdalpur"] },
  { name: "Malkangiri", slug: "malkangiri", state: "Odisha", type: "district", tagline: "Odisha's remote southernmost district, forested and bordering Andhra Pradesh and Chhattisgarh at the Balimela reservoir", context: "the forest-produce and tribal trade, Balimela reservoir fisheries, and agricultural markets", nearby: ["koraput", "nabarangpur", "visakhapatnam", "jagdalpur"] },
  { name: "Gajapati", slug: "gajapati", state: "Odisha", type: "district", tagline: "an Eastern Ghats district centred on the former princely town of Paralakhemundi below Mahendragiri", context: "the turmeric and coffee horticulture trade, tribal handicrafts, and hill tourism", nearby: ["rayagada", "ganjam", "srikakulam", "koraput"] },
  { name: "Kandhamal", slug: "kandhamal", state: "Odisha", type: "district", tagline: "a hill district famed for its GI-tagged Kandhamal turmeric and tribal Kondh culture", context: "the turmeric and spice cultivation trade, tribal handicrafts, and hill tourism", nearby: ["boudh", "ganjam", "nayagarh", "rayagada"] },
  { name: "Boudh", slug: "boudh", state: "Odisha", type: "district", tagline: "a small Mahanadi-riverbank district with an agrarian economy and Buddhist-era heritage", context: "the paddy and turmeric trade, riverbank agriculture, and local wholesale markets", nearby: ["subarnapur", "kandhamal", "angul", "sambalpur"] },
  { name: "Angul", slug: "angul", state: "Odisha", type: "growing", tagline: "an industrial district built on the Talcher coalfields and NALCO's aluminium smelter", context: "the coal-mining and power-plant ancillary industries, aluminium trade, and agricultural markets", nearby: ["dhenkanal", "jharsuguda", "cuttack", "bhubaneswar"] },
  { name: "Dhenkanal", slug: "dhenkanal", state: "Odisha", type: "headquarters", tagline: "a former princely-state district known for its palace heritage and the nearby Satkosia elephant corridor", context: "the handicraft and brass-craft artisan trade, agricultural markets, and heritage tourism", nearby: ["angul", "cuttack", "bhubaneswar", "nayagarh"] },
  { name: "Nayagarh", slug: "nayagarh", state: "Odisha", type: "district", tagline: "a forested former princely-state district on the Mahanadi's Satkosia gorge", context: "the agricultural and forest-produce trade, Satkosia eco-tourism, and local wholesale markets", nearby: ["khordha", "dhenkanal", "kandhamal", "bhubaneswar"] },
  { name: "Deogarh", slug: "deogarh", state: "Odisha", type: "district", tagline: "a small forested district carved from Sambalpur, with an agrarian and forest-produce economy", context: "the agricultural markets, forest-produce trade, and local retail businesses", nearby: ["sambalpur", "angul", "jharsuguda", "bargarh"] },

  /* ══════════════════════════════════════════════
     SIKKIM
  ══════════════════════════════════════════════ */
  { name: "Pakyong", slug: "pakyong", state: "Sikkim", type: "growing", tagline: "a new district built around Sikkim's mountaintop Pakyong Airport", context: "the airport and aviation-ancillary economy, organic cardamom farming, and hill tourism", nearby: ["gangtok", "namchi", "soreng", "mangan"] },
  { name: "Mangan", slug: "mangan", state: "Sikkim", type: "district", tagline: "the North Sikkim headquarters and gateway to the high-Himalayan Yumthang valley", context: "the adventure and eco-tourism trade, cardamom and off-season vegetable farming, and handicrafts", nearby: ["gangtok", "pakyong", "namchi", "gyalshing"] },
  { name: "Namchi", slug: "namchi", state: "Sikkim", type: "growing", tagline: "the South Sikkim headquarters, known for its Char Dham and Samdruptse pilgrimage-tourism complexes", context: "the pilgrimage and tourism trade, large-cardamom farming, and handicraft businesses", nearby: ["gangtok", "pakyong", "gyalshing", "soreng"] },
  { name: "Gyalshing", slug: "gyalshing", state: "Sikkim", type: "growing", tagline: "the West Sikkim headquarters near Pelling, the gateway town for Khangchendzonga views and monasteries", context: "the trekking and monastery-tourism trade, large-cardamom and ginger farming, and handicrafts", nearby: ["namchi", "gangtok", "soreng", "pakyong"] },
  { name: "Soreng", slug: "soreng", state: "Sikkim", type: "district", tagline: "Sikkim's newest district, carved from the west in 2021, with an agrarian cardamom-and-ginger economy", context: "the cardamom and ginger farming trade, local wholesale markets, and developing tourism infrastructure", nearby: ["gyalshing", "namchi", "gangtok", "pakyong"] },

  /* ══════════════════════════════════════════════
     ASSAM
  ══════════════════════════════════════════════ */
  { name: "Kokrajhar", slug: "kokrajhar", state: "Assam", type: "headquarters", tagline: "the headquarters of the Bodoland Territorial Region in western Assam", context: "the Bodo tribal handicraft and weaving trade, agricultural markets, and regional administrative economy", nearby: ["bongaigaon", "dhubri", "guwahati", "barpeta"] },
  { name: "Chirang", slug: "chirang", state: "Assam", type: "district", tagline: "a Bodoland Territorial Region district with a forested, agrarian economy", context: "the agricultural and forest-produce trade, local wholesale markets, and Bodo handicrafts", nearby: ["kokrajhar", "bongaigaon", "baksa", "guwahati"] },
  { name: "Baksa", slug: "baksa", state: "Assam", type: "district", tagline: "a Bodoland Territorial Region district bordering the Manas tiger reserve", context: "the agricultural trade, Manas wildlife-tourism operators, and Bodo handicraft businesses", nearby: ["chirang", "nalbari", "barpeta", "guwahati"] },
  { name: "Barpeta", slug: "barpeta", state: "Assam", type: "headquarters", tagline: "a Brahmaputra-valley district centred on the historic Barpeta Satra Vaishnavite monastery", context: "the Satra pilgrimage economy, paddy and jute trade, and handloom weaving", nearby: ["nalbari", "bongaigaon", "kamrup", "guwahati"] },
  { name: "Bongaigaon", slug: "bongaigaon", state: "Assam", type: "growing", tagline: "an industrial town in lower Assam built around its oil refinery and thermal power plant", context: "the refinery and petrochemical ancillary trade, thermal-power suppliers, and local wholesale markets", nearby: ["kokrajhar", "barpeta", "dhubri", "guwahati"] },
  { name: "South Salmara-Mankachar", slug: "south-salmara-mankachar", state: "Assam", type: "district", tagline: "Assam's smallest and newest district, a Brahmaputra char (river-island) belt bordering Bangladesh", context: "the char-land agriculture, cross-border trade, and river-transport economy", nearby: ["dhubri", "goalpara", "guwahati", "bongaigaon"] },
  { name: "Morigaon", slug: "morigaon", state: "Assam", type: "district", tagline: "a central Assam district home to the rhino-rich Pobitora wildlife sanctuary", context: "the paddy and mustard trade, Pobitora wildlife tourism, and local wholesale markets", nearby: ["nagaon", "guwahati", "kamrup", "hojai"] },
  { name: "Hojai", slug: "hojai", state: "Assam", type: "growing", tagline: "a growing central-Assam trading town on the Guwahati-Silchar national highway", context: "the wholesale and transport trade, paddy agriculture, and local retail", nearby: ["nagaon", "morigaon", "guwahati", "silchar"] },
  { name: "Dima Hasao", slug: "dima-hasao", state: "Assam", type: "district", tagline: "Assam's only hill district, headquartered at the hill station of Haflong", context: "the tribal handicraft and produce trade, hill tourism, and limestone and coal quarrying", nearby: ["silchar", "karbi-anglong", "guwahati", "cachar"] },
  { name: "Sonitpur", slug: "sonitpur", state: "Assam", type: "headquarters", tagline: "the district around Tezpur, stretching north to the Nameri tiger reserve and its tea-garden hinterland", context: "the tea-estate economy beyond Tezpur town, Nameri wildlife-tourism, and agricultural trade", nearby: ["tezpur", "biswanath", "guwahati", "dibrugarh"] },
  { name: "Biswanath", slug: "biswanath", state: "Assam", type: "growing", tagline: "a newer upper-Assam district of tea gardens along the Brahmaputra's northern bank", context: "the tea-estate economy, Kaziranga's northern-range wildlife tourism, and agricultural trade", nearby: ["sonitpur", "tezpur", "dibrugarh", "jorhat"] },
  { name: "Lakhimpur", slug: "lakhimpur", state: "Assam", type: "headquarters", tagline: "an upper-Assam district of tea gardens and paddy fields, gateway to Arunachal Pradesh", context: "the tea-estate economy, paddy and citrus trade, and cross-border logistics", nearby: ["dhemaji", "dibrugarh", "tezpur", "itanagar"] },
  { name: "Dhemaji", slug: "dhemaji", state: "Assam", type: "district", tagline: "a flood-plain district of the upper Brahmaputra, home to a large Mising tribal community", context: "the paddy and jute trade, Mising tribal handicrafts, and flood-resilient agriculture programs", nearby: ["lakhimpur", "dibrugarh", "tezpur", "jorhat"] },
  { name: "Tinsukia", slug: "tinsukia", state: "Assam", type: "headquarters", tagline: "the easternmost Assam district, home to Digboi's historic oil refinery, one of Asia's oldest", context: "the oil and gas ancillary industries, tea-estate economy, and coal trade", nearby: ["dibrugarh", "sivasagar", "jorhat", "itanagar"] },
  { name: "Sivasagar", slug: "sivasagar", state: "Assam", type: "headquarters", tagline: "the historic capital of the six-century Ahom kingdom, famed for the Rang Ghar amphitheatre", context: "the heritage tourism trade, oil and tea ancillary businesses, and agricultural markets", nearby: ["dibrugarh", "jorhat", "tinsukia", "charaideo"] },
  { name: "Charaideo", slug: "charaideo", state: "Assam", type: "district", tagline: "a newer Ahom-heritage district known for the Charaideo Maidams, sometimes called the pyramids of Assam", context: "the heritage tourism trade, tea-estate economy, and agricultural markets", nearby: ["sivasagar", "jorhat", "dibrugarh", "golaghat"] },
  { name: "Majuli", slug: "majuli", state: "Assam", type: "growing", tagline: "the world's largest river island, a Brahmaputra Satra-culture and mask-making centre", context: "the Satra pilgrimage and monastery economy, mask-making and pottery handicrafts, and riverine agriculture", nearby: ["jorhat", "sivasagar", "dibrugarh", "golaghat"] },
  { name: "Golaghat", slug: "golaghat", state: "Assam", type: "headquarters", tagline: "a tea-garden district and the principal gateway town to Kaziranga National Park", context: "the tea-estate economy, Kaziranga wildlife-tourism trade, and agricultural markets", nearby: ["jorhat", "nagaon", "sivasagar", "guwahati"] },
  { name: "Karbi Anglong", slug: "karbi-anglong", state: "Assam", type: "headquarters", tagline: "Assam's largest district, a hill-tribal autonomous region home to the Karbi people", context: "the tribal handicraft and produce trade, forest-fringe agriculture, and local wholesale markets", nearby: ["nagaon", "golaghat", "dima-hasao", "guwahati"] },
  { name: "West Karbi Anglong", slug: "west-karbi-anglong", state: "Assam", type: "district", tagline: "a hill district carved from Karbi Anglong, forested and tribal-majority", context: "the tribal handicraft and produce trade, forest-produce economy, and agricultural markets", nearby: ["karbi-anglong", "morigaon", "nagaon", "guwahati"] },
  { name: "Cachar", slug: "cachar", state: "Assam", type: "headquarters", tagline: "the Barak Valley district anchored by Silchar, Assam's second-largest urban agglomeration", context: "the tea-estate and rubber-plantation economy beyond Silchar town, paddy trade, and cross-valley logistics", nearby: ["silchar", "hailakandi", "karimganj", "guwahati"] },
  { name: "Hailakandi", slug: "hailakandi", state: "Assam", type: "district", tagline: "a Barak Valley district known for its rubber plantations and paddy agriculture", context: "the rubber-plantation economy, paddy and betel-nut trade, and local wholesale markets", nearby: ["silchar", "karimganj", "cachar", "guwahati"] },
  { name: "Karimganj", slug: "karimganj", state: "Assam", type: "headquarters", tagline: "a Barak Valley border district trading across the Bangladesh frontier", context: "the cross-border trade, tea and betel-nut plantations, and paddy agriculture", nearby: ["silchar", "hailakandi", "cachar", "guwahati"] },
  { name: "Kamrup Metropolitan", slug: "kamrup-metropolitan", state: "Assam", type: "headquarters", tagline: "Assam's metropolitan district, covering Guwahati city and the state capital seat of Dispur", context: "the metropolitan administrative and IT economy, Dispur's government offices, and the Guwahati urban trade base", nearby: ["guwahati", "kamrup", "nalbari", "morigaon"] },
  { name: "Kamrup", slug: "kamrup", state: "Assam", type: "headquarters", tagline: "the rural district ringing Guwahati, home to the Hajo pilgrimage town and Rangia trade hub", context: "the Hajo multi-faith pilgrimage economy, Rangia's agricultural trade, and Guwahati-linked logistics", nearby: ["guwahati", "kamrup-metropolitan", "nalbari", "barpeta"] },
  { name: "Nalbari", slug: "nalbari", state: "Assam", type: "headquarters", tagline: "a lower-Assam district known for its handloom weaving and paddy agriculture near Guwahati", context: "the handloom and gamosa-weaving trade, paddy agriculture, and local wholesale markets", nearby: ["barpeta", "kamrup", "baksa", "guwahati"] },
  { name: "Dhubri", slug: "dhubri", state: "Assam", type: "headquarters", tagline: "a Brahmaputra river-port district on the Bangladesh border in lower Assam", context: "the river-port and jute trade, char-land agriculture, and cross-border wholesale markets", nearby: ["goalpara", "south-salmara-mankachar", "kokrajhar", "guwahati"] },
  { name: "Goalpara", slug: "goalpara", state: "Assam", type: "district", tagline: "a historic Brahmaputra river-port town in lower Assam", context: "the river-trade and jute economy, agricultural markets, and small-scale coal trade", nearby: ["dhubri", "kamrup", "bongaigaon", "guwahati"] },
  { name: "Darrang", slug: "darrang", state: "Assam", type: "district", tagline: "a middle-Assam district headquartered at Mangaldoi, with a paddy-and-tea agrarian economy", context: "the tea-estate and paddy trade, agricultural markets, and local wholesale businesses", nearby: ["udalguri", "sonitpur", "guwahati", "tezpur"] },
  { name: "Udalguri", slug: "udalguri", state: "Assam", type: "district", tagline: "a Bodoland Territorial Region district in the Bhutan foothills of middle Assam", context: "the agricultural and forest-fringe trade, Bodo handicrafts, and cross-border markets with Bhutan", nearby: ["darrang", "sonitpur", "baksa", "guwahati"] },
  { name: "Bajali", slug: "bajali", state: "Assam", type: "district", tagline: "one of Assam's newest districts, carved from Barpeta in 2021, with an agrarian paddy economy", context: "the paddy and jute trade, handloom weaving, and local wholesale markets", nearby: ["barpeta", "nalbari", "kamrup", "guwahati"] },
];
