import type { CityInfo } from "@/lib/localSeo";

/* Remaining real district headquarters for Uttar Pradesh, Bihar, Jharkhand,
   Uttarakhand and Himachal Pradesh not yet covered by the hand-authored
   upCities / biharCities / jharkhandCities / uttarakhandCities arrays (and
   the two HP entries in northeastHimalayanAndUtCities) in lib/localSeo.ts. */
export const group1Cities: CityInfo[] = [
  // ══════════════ UTTAR PRADESH ══════════════
  { name: "Mainpuri", slug: "mainpuri", state: "Uttar Pradesh", type: "district", tagline: "an agricultural district headquarters on the Etawah-Agra corridor known for its tobacco trade", context: "the tobacco and grain trade, agricultural markets, and local wholesalers", nearby: ["etawah", "firozabad", "agra", "farrukhabad"] },
  { name: "Etah", slug: "etah", state: "Uttar Pradesh", type: "district", tagline: "an agricultural district headquarters in the Ganga-Yamuna doab of western UP", context: "the grain and potato trade, agricultural equipment dealers, and local retail", nearby: ["aligarh", "mainpuri", "kasganj", "firozabad"] },
  { name: "Hathras", slug: "hathras", state: "Uttar Pradesh", type: "district", tagline: "a hosiery and hardware manufacturing town near Aligarh", context: "the hosiery and hardware units, agricultural trade, and local wholesalers", nearby: ["aligarh", "mathura", "agra", "etah"] },
  { name: "Kasganj", slug: "kasganj", state: "Uttar Pradesh", type: "district", tagline: "a sugar-belt district headquarters carved from Etah district", context: "the sugar mills, agricultural trade, and local markets", nearby: ["etah", "aligarh", "badaun", "farrukhabad"] },
  { name: "Ambedkar Nagar", slug: "ambedkar-nagar", state: "Uttar Pradesh", type: "district", tagline: "an Awadh district headquarters (Akbarpur-Tanda) with a handloom weaving tradition", context: "the handloom weaving units, agricultural trade, and local wholesalers", nearby: ["faizabad", "sultanpur", "azamgarh", "gonda"] },
  { name: "Amethi", slug: "amethi", state: "Uttar Pradesh", type: "district", tagline: "an Awadh district headquarters carved from Sultanpur and Rae Bareli", context: "the agricultural trade, small-scale manufacturing, and local retail", nearby: ["sultanpur", "rae-bareli", "faizabad", "lucknow"] },
  { name: "Kaushambi", slug: "kaushambi", state: "Uttar Pradesh", type: "district", tagline: "an ancient Buddhist-era district headquarters near Prayagraj on the Yamuna", context: "the agricultural trade, heritage tourism, and local markets", nearby: ["prayagraj", "fatehpur", "pratapgarh", "banda"] },
  { name: "Sant Kabir Nagar", slug: "sant-kabir-nagar", state: "Uttar Pradesh", type: "district", tagline: "a Purvanchal district headquarters named for the poet-saint Kabir", context: "the agricultural trade, small retail, and local service providers", nearby: ["basti", "gorakhpur", "siddharthnagar", "deoria"] },
  { name: "Siddharthnagar", slug: "siddharthnagar", state: "Uttar Pradesh", type: "district", tagline: "a Terai district headquarters bordering Nepal, named for the Buddha", context: "the cross-border trade, agricultural markets, and local retail", nearby: ["basti", "gorakhpur", "maharajganj", "sant-kabir-nagar"] },
  { name: "Chitrakoot", slug: "chitrakoot", state: "Uttar Pradesh", type: "growing", tagline: "a sacred Ramayana-era pilgrimage town shared with Madhya Pradesh", context: "the pilgrimage tourism, handicraft businesses, and agricultural trade", nearby: ["banda", "prayagraj", "kaushambi", "mahoba"] },
  { name: "Hamirpur", slug: "hamirpur", state: "Uttar Pradesh", type: "district", tagline: "a Bundelkhand district headquarters at the Yamuna-Betwa confluence", context: "the agricultural trade, stone-crushing units, and local markets", nearby: ["banda", "mahoba", "jhansi", "jalaun"] },
  { name: "Mahoba", slug: "mahoba", state: "Uttar Pradesh", type: "district", tagline: "a historic Bundelkhand district headquarters known for its Chandela-era temples and granite trade", context: "the granite quarrying units, heritage tourism, and agricultural trade", nearby: ["hamirpur", "banda", "jhansi", "chitrakoot"] },
  { name: "Balrampur", slug: "balrampur", state: "Uttar Pradesh", type: "district", tagline: "a Terai sugar-belt district headquarters bordering Nepal", context: "the sugar mills, agricultural trade, and cross-border markets", nearby: ["gonda", "shravasti", "bahraich", "siddharthnagar"] },
  { name: "Shravasti", slug: "shravasti", state: "Uttar Pradesh", type: "district", tagline: "an ancient Buddhist pilgrimage district headquarters in the Terai belt", context: "the pilgrimage tourism, agricultural trade, and local markets", nearby: ["balrampur", "bahraich", "gonda", "gorakhpur"] },
  { name: "Kushinagar", slug: "kushinagar", state: "Uttar Pradesh", type: "growing", tagline: "the site of Buddha's Mahaparinirvana and a growing international pilgrimage hub", context: "the pilgrimage tourism and hospitality trade, sugar mills, and agricultural markets", nearby: ["gorakhpur", "deoria", "maharajganj", "basti"] },
  { name: "Maharajganj", slug: "maharajganj", state: "Uttar Pradesh", type: "district", tagline: "a Nepal-border district headquarters with active cross-border trade", context: "the cross-border trade, agricultural markets, and local wholesalers", nearby: ["gorakhpur", "kushinagar", "siddharthnagar", "sant-kabir-nagar"] },
  { name: "Jalaun", slug: "jalaun", state: "Uttar Pradesh", type: "district", tagline: "a Bundelkhand district headquarters on the Yamuna-Pahuj corridor", context: "the agricultural trade, stone and gravel units, and local markets", nearby: ["hamirpur", "jhansi", "etawah", "auraiya"] },
  { name: "Lalitpur", slug: "lalitpur", state: "Uttar Pradesh", type: "district", tagline: "a Bundelkhand district headquarters bordering Madhya Pradesh, rich in granite", context: "the granite mining units, agricultural trade, and local retail", nearby: ["jhansi", "jalaun", "tikamgarh", "hamirpur"] },
  { name: "Kanpur Dehat", slug: "kanpur-dehat", state: "Uttar Pradesh", type: "district", tagline: "the rural district around Kanpur, with an agrarian and small-industry economy", context: "the agricultural trade, small manufacturing units, and local markets", nearby: ["kanpur", "kanpur-nagar", "etawah", "farrukhabad"] },
  { name: "Auraiya", slug: "auraiya", state: "Uttar Pradesh", type: "district", tagline: "an industrial-agricultural district headquarters with a large gas-based power plant", context: "the power and energy ancillary units, agricultural trade, and local markets", nearby: ["etawah", "kanpur-dehat", "jalaun", "farrukhabad"] },
  { name: "Baghpat", slug: "baghpat", state: "Uttar Pradesh", type: "growing", tagline: "an NCR-adjacent sugarcane-belt district on the Delhi-Meerut corridor", context: "the sugar mills, agricultural trade, and small manufacturing units", nearby: ["meerut", "ghaziabad", "noida", "muzaffarnagar"] },
  { name: "Sonbhadra", slug: "sonbhadra", state: "Uttar Pradesh", type: "growing", tagline: "an energy and mineral-belt district headquarters on the Vindhya plateau", context: "the thermal-power and mining ancillary units, forest-produce trade, and local markets", nearby: ["mirzapur", "prayagraj", "rewa", "chitrakoot"] },
  { name: "Shamli", slug: "shamli", state: "Uttar Pradesh", type: "growing", tagline: "a sugarcane and paper-mill district headquarters in western UP", context: "the sugar and paper mills, agricultural trade, and local wholesalers", nearby: ["muzaffarnagar", "saharanpur", "baghpat", "meerut"] },
  { name: "Chandauli", slug: "chandauli", state: "Uttar Pradesh", type: "district", tagline: "a rice-belt district headquarters adjoining Varanasi", context: "the rice milling and trade, agricultural markets, and local retail", nearby: ["varanasi", "ghazipur", "mirzapur", "sant-ravidas-nagar"] },

  // ══════════════ BIHAR ══════════════
  { name: "Kaimur", slug: "kaimur", state: "Bihar", type: "district", tagline: "a forested plateau district headquarters at Bhabua on the Bihar-UP border", context: "the stone and mineral trade, forest-fringe agriculture, and local markets", nearby: ["sasaram", "rohtas", "chandauli", "ara"] },
  { name: "Arwal", slug: "arwal", state: "Bihar", type: "district", tagline: "a young district carved from Jehanabad on the banks of the Son river", context: "the agricultural trade, local retail markets, and small contractors", nearby: ["jehanabad", "gaya", "patna", "nalanda"] },

  // ══════════════ JHARKHAND ══════════════

  // ══════════════ UTTARAKHAND ══════════════
  { name: "Uttarkashi", slug: "uttarkashi", state: "Uttarakhand", type: "growing", tagline: "a Himalayan pilgrimage district headquarters and gateway to the Gangotri and Yamunotri shrines", context: "the pilgrimage and trekking tourism, hospitality businesses, and horticulture trade", nearby: ["dehradun", "rishikesh", "chamoli", "tehri-garhwal"] },
  { name: "Chamoli", slug: "chamoli", state: "Uttarakhand", type: "growing", tagline: "a Himalayan district headquarters and gateway to Badrinath, Valley of Flowers and Auli", context: "the pilgrimage and adventure tourism, horticulture trade, and hospitality businesses", nearby: ["rudraprayag", "pauri-garhwal", "haridwar", "dehradun"] },
  { name: "Rudraprayag", slug: "rudraprayag", state: "Uttarakhand", type: "growing", tagline: "the sacred confluence town on the pilgrimage route to Kedarnath and Badrinath", context: "the pilgrimage tourism, hospitality businesses, and horticulture trade", nearby: ["chamoli", "pauri-garhwal", "haridwar", "tehri-garhwal"] },
  { name: "Pauri Garhwal", slug: "pauri-garhwal", state: "Uttarakhand", type: "growing", tagline: "a scenic Garhwal district headquarters and defence-recruitment hub", context: "the tourism and hospitality trade, horticulture, and defence-linked economy", nearby: ["dehradun", "rishikesh", "haridwar", "haldwani"] },
  { name: "Tehri Garhwal", slug: "tehri-garhwal", state: "Uttarakhand", type: "growing", tagline: "a Himalayan district headquarters known for the Tehri Dam and reservoir tourism", context: "the hydropower ancillary trade, adventure and lake tourism, and horticulture", nearby: ["dehradun", "rishikesh", "uttarkashi", "pauri-garhwal"] },
  { name: "Almora", slug: "almora", state: "Uttarakhand", type: "growing", tagline: "a historic Kumaon hill-station district headquarters known for its heritage and horticulture", context: "the tourism and hospitality trade, fruit and herb processing, and handicraft businesses", nearby: ["nainital", "haldwani", "bageshwar", "pithoragarh"] },
  { name: "Bageshwar", slug: "bageshwar", state: "Uttarakhand", type: "district", tagline: "a Himalayan Kumaon district headquarters at the confluence of the Saryu and Gomti rivers", context: "the pilgrimage tourism, horticulture trade, and local markets", nearby: ["almora", "pithoragarh", "chamoli", "haldwani"] },
  { name: "Champawat", slug: "champawat", state: "Uttarakhand", type: "district", tagline: "a scenic Kumaon border district headquarters near the Nepal frontier", context: "the tourism and hospitality trade, horticulture, and cross-border markets", nearby: ["pithoragarh", "almora", "haldwani", "nainital"] },
  { name: "Nainital", slug: "nainital", state: "Uttarakhand", type: "major", tagline: "a premier Himalayan lake-district headquarters and one of India's best-known hill stations", context: "the tourism and hospitality trade, education institutions, and horticulture", nearby: ["haldwani", "almora", "rudrapur", "champawat"] },
  { name: "Pithoragarh", slug: "pithoragarh", state: "Uttarakhand", type: "growing", tagline: "a remote Himalayan border district headquarters near the Nepal and Tibet frontiers", context: "the cross-border and defence-linked trade, tourism, and horticulture", nearby: ["champawat", "bageshwar", "almora", "haldwani"] },
  { name: "Udham Singh Nagar", slug: "udham-singh-nagar", state: "Uttarakhand", type: "growing", tagline: "the industrial (SIDCUL) and agricultural Terai belt around Rudrapur and Kashipur", context: "the automobile and FMCG manufacturing units, agricultural markets, and industrial suppliers", nearby: ["rudrapur", "haldwani", "nainital", "bareilly"] },

  // ══════════════ HIMACHAL PRADESH ══════════════
  { name: "Chamba", slug: "chamba", state: "Himachal Pradesh", type: "growing", tagline: "a remote Himalayan district headquarters famed for its temple architecture and handicrafts", context: "the handicraft and Chamba rumal embroidery trade, tourism, and horticulture", nearby: ["kangra", "dharamshala", "una", "mandi"] },
  { name: "Kangra", slug: "kangra", state: "Himachal Pradesh", type: "headquarters", tagline: "the tea-growing valley district headquarters that is home to Dharamshala and McLeod Ganj", context: "the tea estates, hospitality and homestay trade, and horticulture", nearby: ["dharamshala", "una", "chamba", "hamirpur-hp"] },
  { name: "Una", slug: "una", state: "Himachal Pradesh", type: "growing", tagline: "an industrial gateway district headquarters bordering Punjab", context: "the manufacturing and industrial estates, agricultural trade, and local markets", nearby: ["hamirpur-hp", "kangra", "bilaspur-hp", "hoshiarpur"] },
  { name: "Hamirpur HP", slug: "hamirpur-hp", state: "Himachal Pradesh", type: "growing", tagline: "a hill-district headquarters known for its high literacy and army-recruitment tradition", context: "the education institutions, remittance-funded retail, and horticulture trade", nearby: ["una", "bilaspur-hp", "kangra", "mandi"] },
  { name: "Kullu", slug: "kullu", state: "Himachal Pradesh", type: "major", tagline: "the Kullu Valley district headquarters, a premier apple-horticulture and adventure-tourism destination", context: "the apple horticulture supply chains, adventure tourism, and hospitality businesses", nearby: ["mandi", "shimla", "kinnaur", "lahaul-and-spiti"] },
  { name: "Mandi", slug: "mandi", state: "Himachal Pradesh", type: "headquarters", tagline: "a historic temple-town district headquarters and hydropower hub of central Himachal", context: "the hydropower ancillary trade, heritage tourism, and agricultural markets", nearby: ["kullu", "hamirpur-hp", "bilaspur-hp", "shimla"] },
  { name: "Lahaul and Spiti", slug: "lahaul-and-spiti", state: "Himachal Pradesh", type: "district", tagline: "a high-altitude trans-Himalayan district headquarters, one of India's most remote tourism destinations", context: "the adventure and monastery tourism, horticulture (seed potato, peas), and hospitality", nearby: ["kullu", "kinnaur", "mandi", "shimla"] },
  { name: "Kinnaur", slug: "kinnaur", state: "Himachal Pradesh", type: "district", tagline: "a Himalayan border district headquarters famed for its apple and dry-fruit orchards", context: "the apple and dry-fruit horticulture, hydropower ancillary trade, and tourism", nearby: ["shimla", "kullu", "lahaul-and-spiti", "sirmaur"] },
  { name: "Sirmaur", slug: "sirmaur", state: "Himachal Pradesh", type: "growing", tagline: "a foothill district headquarters bordering Haryana and Uttarakhand, with growing industrial estates", context: "the pharma and manufacturing units, horticulture trade, and tourism", nearby: ["solan", "shimla", "yamunanagar", "dehradun"] },
  { name: "Solan", slug: "solan", state: "Himachal Pradesh", type: "growing", tagline: "the mushroom capital of India and a fast-growing pharma-manufacturing district headquarters", context: "the pharma manufacturing units, mushroom cultivation, and horticulture trade", nearby: ["shimla", "sirmaur", "chandigarh", "bilaspur-hp"] },
  { name: "Bilaspur HP", slug: "bilaspur-hp", state: "Himachal Pradesh", type: "growing", tagline: "a reservoir-side district headquarters on the Govind Sagar lake formed by the Bhakra Dam", context: "the hydropower ancillary trade, lake tourism, and agricultural markets", nearby: ["una", "hamirpur-hp", "solan", "mandi"] },
];
