import type { CityInfo } from "@/lib/localSeo";

/* Skipped 3 of the 80 input entries because their real headquarters town is
   already a covered city elsewhere in lib/localSeo.ts, and adding them here
   under an administrative-district name would just be a duplicate page about
   the same place:
     - Goa "North Goa"  -> HQ is Panaji, already covered (otherCities)
     - Goa "South Goa"  -> HQ is Margao, already covered (otherCities)
     - "Dadra and Nagar Haveli" -> HQ is Silvassa, already covered (otherCities)
   Diu is kept: it's a separate island territory from Daman, not the same
   place under another name. */

export const group5Cities: CityInfo[] = [
  // ═══════════ MADHYA PRADESH ═══════════
  { name: "Raisen", slug: "raisen", state: "Madhya Pradesh", type: "headquarters", tagline: "the district headquarters near Bhopal, home to the ancient Buddhist stupa complex at Sanchi and the Mandideep industrial belt", context: "the Mandideep industrial estate, Sanchi heritage tourism, and agricultural trade", nearby: ["bhopal", "vidisha", "sehore", "narmadapuram"] },
  { name: "Rajgarh", slug: "rajgarh", state: "Madhya Pradesh", type: "district", tagline: "a Malwa-plateau district headquarters in the state's soybean-and-wheat farm belt", context: "the soybean and grain trade, agricultural markets, and local retail", nearby: ["bhopal", "sehore", "guna", "vidisha"] },
  { name: "Sehore", slug: "sehore", state: "Madhya Pradesh", type: "growing", tagline: "a Malwa-plateau district headquarters often called one of India's leading soybean-growing areas", context: "the soybean processing and trade, agricultural mandis, and local wholesalers", nearby: ["bhopal", "raisen", "rajgarh", "dewas"] },
  { name: "Vidisha", slug: "vidisha", state: "Madhya Pradesh", type: "headquarters", tagline: "an ancient Malwa city on the heritage circuit near Sanchi's Buddhist monuments", context: "the heritage tourism, agricultural mandis, and local trade", nearby: ["bhopal", "raisen", "guna", "ashoknagar"] },
  { name: "Dhar", slug: "dhar", state: "Madhya Pradesh", type: "growing", tagline: "a historic Malwa fort city near the Mandu heritage circuit and the Pithampur auto-industrial belt", context: "the auto-ancillary units around Pithampur, heritage tourism, and agricultural trade", nearby: ["indore", "khargone", "jhabua", "ratlam"] },
  { name: "Jhabua", slug: "jhabua", state: "Madhya Pradesh", type: "district", tagline: "a tribal Bhil-heartland district headquarters on MP's western border with Gujarat and Rajasthan", context: "the agricultural and forest-produce trade, tribal cooperative businesses, and local markets", nearby: ["dhar", "alirajpur", "ratlam", "indore"] },
  { name: "Alirajpur", slug: "alirajpur", state: "Madhya Pradesh", type: "district", tagline: "a remote tribal district headquarters in MP's Bhil belt, carved out of Jhabua", context: "the agricultural markets, forest-produce trade, and local retail", nearby: ["jhabua", "dhar", "barwani", "khargone"] },
  { name: "Barwani", slug: "barwani", state: "Madhya Pradesh", type: "district", tagline: "a Narmada-valley district headquarters in MP's tribal southwest", context: "the agricultural trade, Narmada-basin horticulture, and local markets", nearby: ["khargone", "dhar", "alirajpur", "khandwa"] },
  { name: "Khandwa", slug: "khandwa", state: "Madhya Pradesh", type: "headquarters", tagline: "the headquarters of East Nimar, a cotton-trading town on the Narmada known as playback singer Kishore Kumar's birthplace", context: "the cotton ginning mills, oilseed trade, and agricultural markets", nearby: ["khargone", "burhanpur", "indore", "dewas"] },
  { name: "Khargone", slug: "khargone", state: "Madhya Pradesh", type: "headquarters", tagline: "the headquarters of West Nimar, at the heart of MP's cotton and chilli-growing belt", context: "the cotton and chilli trade, ginning mills, and agricultural markets", nearby: ["khandwa", "barwani", "dhar", "indore"] },
  { name: "Burhanpur", slug: "burhanpur", state: "Madhya Pradesh", type: "growing", tagline: "a historic Mughal-era textile town on the Tapi, now a leading banana-growing belt", context: "the banana cultivation and trade, textile weaving units, and agricultural markets", nearby: ["khandwa", "khargone", "indore", "dewas"] },
  { name: "Dewas", slug: "dewas", state: "Madhya Pradesh", type: "growing", tagline: "an industrial satellite town on the Indore-Dewas corridor, home to India's currency note press", context: "the pharmaceutical and FMCG manufacturing units, the security press, and agricultural trade", nearby: ["indore", "ujjain", "sehore", "shajapur"] },
  { name: "Mandsaur", slug: "mandsaur", state: "Madhya Pradesh", type: "headquarters", tagline: "a Malwa mandi town at the center of India's licensed opium-poppy cultivation belt", context: "the opium and mandi-crop trade, agricultural markets, and local wholesalers", nearby: ["neemuch", "ratlam", "ujjain", "shajapur"] },
  { name: "Neemuch", slug: "neemuch", state: "Madhya Pradesh", type: "growing", tagline: "a Malwa cantonment town and major opium-licensed cultivation and trading center", context: "the opium and mandi-crop trade, defence-cantonment economy, and agricultural markets", nearby: ["mandsaur", "ratlam", "ujjain", "shajapur"] },
  { name: "Ratlam", slug: "ratlam", state: "Madhya Pradesh", type: "headquarters", tagline: "a major railway junction and trading town at the heart of the Malwa grain-and-opium belt", context: "the railway ancillary trade, agricultural mandis, and textile and namkeen units", nearby: ["mandsaur", "neemuch", "ujjain", "dhar"] },
  { name: "Shajapur", slug: "shajapur", state: "Madhya Pradesh", type: "district", tagline: "a Malwa-plateau district headquarters with a soybean-and-wheat mandi economy", context: "the agricultural mandis, grain trade, and local wholesalers", nearby: ["dewas", "ujjain", "agar-malwa", "rajgarh"] },
  { name: "Agar Malwa", slug: "agar-malwa", state: "Madhya Pradesh", type: "district", tagline: "one of MP's newest districts, a Malwa opium and mandi-crop town carved out of Shajapur", context: "the opium-licensed cultivation, agricultural mandis, and local trade", nearby: ["shajapur", "ujjain", "rajgarh", "mandsaur"] },
  { name: "Narmadapuram", slug: "narmadapuram", state: "Madhya Pradesh", type: "headquarters", tagline: "the district formerly known as Hoshangabad, on the Narmada and gateway to the Pachmarhi hill station", context: "the Pachmarhi hill-station tourism, agricultural trade, and small industrial units", nearby: ["bhopal", "betul", "harda", "raisen"] },
  { name: "Betul", slug: "betul", state: "Madhya Pradesh", type: "growing", tagline: "a forested Satpura-hills district headquarters in the Mahakoshal region", context: "the agricultural and cotton trade, forest-produce businesses, and local markets", nearby: ["chhindwara", "narmadapuram", "harda", "narsinghpur"] },
  { name: "Harda", slug: "harda", state: "Madhya Pradesh", type: "district", tagline: "a Narmada-valley district headquarters known for its wheat and soybean mandi", context: "the grain mandi trade, agricultural markets, and local wholesalers", nearby: ["narmadapuram", "betul", "dewas", "khandwa"] },
  { name: "Shivpuri", slug: "shivpuri", state: "Madhya Pradesh", type: "growing", tagline: "a Gwalior-Chambal region district headquarters known for its national park and Scindia-era heritage", context: "the wildlife tourism, agricultural trade, and stone-quarrying businesses", nearby: ["gwalior", "guna", "datia", "ashoknagar"] },
  { name: "Guna", slug: "guna", state: "Madhya Pradesh", type: "growing", tagline: "a Gwalior-Chambal region trading town on the historic Malwa-Central India route", context: "the agricultural mandis, grain trade, and local wholesalers", nearby: ["shivpuri", "ashoknagar", "rajgarh", "vidisha"] },
  { name: "Ashoknagar", slug: "ashoknagar", state: "Madhya Pradesh", type: "district", tagline: "a district headquarters carved out of Guna, with a soybean-and-wheat mandi economy", context: "the agricultural mandis, grain trade, and local retail", nearby: ["guna", "vidisha", "shivpuri", "datia"] },
  { name: "Datia", slug: "datia", state: "Madhya Pradesh", type: "district", tagline: "a historic Bundelkhand-edge palace town on the Gwalior-Jhansi corridor", context: "the heritage tourism, agricultural trade, and local wholesalers", nearby: ["gwalior", "shivpuri", "jhansi", "ashoknagar"] },
  { name: "Morena", slug: "morena", state: "Madhya Pradesh", type: "growing", tagline: "a Chambal-ravine district headquarters and major mustard-oilseed trading center", context: "the mustard-oil milling, agricultural mandis, and local wholesalers", nearby: ["gwalior", "bhind", "sheopur", "agra"] },
  { name: "Bhind", slug: "bhind", state: "Madhya Pradesh", type: "district", tagline: "a Chambal-region district headquarters known for its mustard cultivation and milling", context: "the mustard-oil milling, agricultural trade, and local markets", nearby: ["morena", "gwalior", "datia", "agra"] },
  { name: "Sheopur", slug: "sheopur", state: "Madhya Pradesh", type: "district", tagline: "a remote Chambal-border district headquarters, home to the Kuno National Park cheetah-reintroduction project", context: "the wildlife-tourism trade, agricultural markets, and local retail", nearby: ["morena", "shivpuri", "gwalior", "kota"] },
  { name: "Chhatarpur", slug: "chhatarpur", state: "Madhya Pradesh", type: "growing", tagline: "the Bundelkhand gateway town to the Khajuraho temple World Heritage site", context: "the heritage and temple tourism, agricultural trade, and local hospitality businesses", nearby: ["panna", "tikamgarh", "damoh", "satna"] },
  { name: "Damoh", slug: "damoh", state: "Madhya Pradesh", type: "district", tagline: "a Bundelkhand-Mahakoshal transition district headquarters with an agrarian mandi economy", context: "the agricultural mandis, grain trade, and local wholesalers", nearby: ["sagar", "chhatarpur", "panna", "katni"] },
  { name: "Tikamgarh", slug: "tikamgarh", state: "Madhya Pradesh", type: "district", tagline: "a historic Bundelkhand district headquarters known for its palace-era heritage", context: "the agricultural trade, heritage tourism, and local retail", nearby: ["chhatarpur", "niwari", "panna", "sagar"] },
  { name: "Panna", slug: "panna", state: "Madhya Pradesh", type: "growing", tagline: "India's only diamond-mining district and a Bundelkhand tiger-reserve town", context: "the diamond mining trade, wildlife tourism, and agricultural markets", nearby: ["chhatarpur", "satna", "tikamgarh", "damoh"] },
  { name: "Niwari", slug: "niwari", state: "Madhya Pradesh", type: "district", tagline: "one of MP's newest districts, carved out of Tikamgarh in the Bundelkhand belt", context: "the agricultural trade, local mandis, and small retail businesses", nearby: ["tikamgarh", "chhatarpur", "datia", "jhansi"] },
  { name: "Satna", slug: "satna", state: "Madhya Pradesh", type: "headquarters", tagline: "the cement capital of the Vindhya region and a major Baghelkhand trading town", context: "the cement-plant ancillary units, agricultural mandis, and limestone trade", nearby: ["rewa", "panna", "chhatarpur", "maihar"] },
  { name: "Sidhi", slug: "sidhi", state: "Madhya Pradesh", type: "district", tagline: "a Baghelkhand-region district headquarters with a coal-and-power ancillary economy", context: "the coal-mining trade, power-plant suppliers, and agricultural markets", nearby: ["singrauli", "rewa", "shahdol", "satna"] },
  { name: "Singrauli", slug: "singrauli", state: "Madhya Pradesh", type: "growing", tagline: "often called the energy capital of India, a coalfield and thermal-power hub on the MP-UP border", context: "the coal mining and thermal-power ancillary units, industrial suppliers, and trade", nearby: ["sidhi", "rewa", "shahdol", "sonbhadra"] },
  { name: "Mauganj", slug: "mauganj", state: "Madhya Pradesh", type: "district", tagline: "one of MP's newest districts, carved out of Rewa in the Baghelkhand plains", context: "the agricultural mandis, grain trade, and local retail", nearby: ["rewa", "satna", "sidhi", "prayagraj"] },
  { name: "Maihar", slug: "maihar", state: "Madhya Pradesh", type: "district", tagline: "a Baghelkhand temple town on the Sharda Devi pilgrimage circuit, newly made its own district", context: "the pilgrimage tourism, cement-belt trade, and agricultural markets", nearby: ["satna", "rewa", "panna", "katni"] },
  { name: "Katni", slug: "katni", state: "Madhya Pradesh", type: "headquarters", tagline: "a limestone-and-cement industrial town and major railway junction of the Mahakoshal region", context: "the cement-plant ancillary units, railway trade, and mineral businesses", nearby: ["jabalpur", "satna", "damoh", "umaria"] },
  { name: "Narsinghpur", slug: "narsinghpur", state: "Madhya Pradesh", type: "growing", tagline: "a fertile Narmada-valley district often called Madhya Pradesh's wheat bowl", context: "the wheat and grain mandis, agricultural trade, and local wholesalers", nearby: ["jabalpur", "narmadapuram", "chhindwara", "seoni"] },
  { name: "Dindori", slug: "dindori", state: "Madhya Pradesh", type: "district", tagline: "a tribal Mahakoshal district near the Narmada's source at Amarkantak", context: "the pilgrimage and eco-tourism, forest-produce trade, and agricultural markets", nearby: ["mandla", "shahdol", "anuppur", "jabalpur"] },
  { name: "Mandla", slug: "mandla", state: "Madhya Pradesh", type: "growing", tagline: "a Gond-tribal-heartland district headquarters and gateway to Kanha National Park", context: "the wildlife-tourism trade, forest-produce businesses, and agricultural markets", nearby: ["jabalpur", "dindori", "balaghat", "seoni"] },
  { name: "Balaghat", slug: "balaghat", state: "Madhya Pradesh", type: "growing", tagline: "a forested Mahakoshal district on the Maharashtra border, known for manganese mining", context: "the manganese mining trade, forest-produce businesses, and agricultural markets", nearby: ["mandla", "seoni", "jabalpur", "balod"] },
  { name: "Shahdol", slug: "shahdol", state: "Madhya Pradesh", type: "headquarters", tagline: "a Baghelkhand coalfield district headquarters in eastern Madhya Pradesh", context: "the coal-mining trade, power-ancillary units, and agricultural markets", nearby: ["umaria", "anuppur", "sidhi", "dindori"] },
  { name: "Umaria", slug: "umaria", state: "Madhya Pradesh", type: "district", tagline: "the gateway district to Bandhavgarh National Park's tiger reserve", context: "the wildlife-tourism trade, coal-mining businesses, and agricultural markets", nearby: ["shahdol", "katni", "sidhi", "anuppur"] },
  { name: "Anuppur", slug: "anuppur", state: "Madhya Pradesh", type: "district", tagline: "a Mahakoshal coalfield district near the Amarkantak plateau pilgrimage site", context: "the coal-mining trade, pilgrimage tourism, and agricultural markets", nearby: ["shahdol", "dindori", "umaria", "bilaspur"] },
  { name: "Chhindwara", slug: "chhindwara", state: "Madhya Pradesh", type: "headquarters", tagline: "a Mahakoshal district headquarters known for its orange orchards and coal mining", context: "the orange cultivation and trade, coal-mining ancillary units, and agricultural markets", nearby: ["betul", "seoni", "narsinghpur", "pandhurna"] },
  { name: "Pandhurna", slug: "pandhurna", state: "Madhya Pradesh", type: "district", tagline: "one of MP's newest districts, carved out of Chhindwara in the orange-growing belt bordering Maharashtra", context: "the orange cultivation and trade, agricultural mandis, and local retail", nearby: ["chhindwara", "betul", "narsinghpur", "nagpur"] },
  { name: "Seoni", slug: "seoni", state: "Madhya Pradesh", type: "growing", tagline: "a forested Mahakoshal district and gateway to Pench National Park, the setting for The Jungle Book", context: "the wildlife-tourism trade, forest-produce businesses, and agricultural markets", nearby: ["chhindwara", "balaghat", "mandla", "nagpur"] },

  // ═══════════ CHHATTISGARH ═══════════
  { name: "Baloda Bazar-Bhatapara", slug: "baloda-bazar-bhatapara", state: "Chhattisgarh", type: "district", tagline: "a rice-and-cement belt district carved out of Raipur in central Chhattisgarh", context: "the rice-mill trade, cement-plant ancillary units, and agricultural markets", nearby: ["raipur", "mahasamund", "bilaspur", "dhamtari"] },
  { name: "Dhamtari", slug: "dhamtari", state: "Chhattisgarh", type: "growing", tagline: "a canal-irrigated rice-bowl district headquarters south of Raipur", context: "the rice-mill trade, agricultural mandis, and local wholesalers", nearby: ["raipur", "mahasamund", "gariaband", "kondagaon"] },
  { name: "Gariaband", slug: "gariaband", state: "Chhattisgarh", type: "district", tagline: "a forested tribal district carved out of Raipur, on Chhattisgarh's Odisha border", context: "the forest-produce trade, agricultural markets, and local retail", nearby: ["raipur", "dhamtari", "mahasamund", "baloda-bazar-bhatapara"] },
  { name: "Mahasamund", slug: "mahasamund", state: "Chhattisgarh", type: "growing", tagline: "a rice-mandi district headquarters on the Chhattisgarh-Odisha trade corridor", context: "the rice-mill trade, agricultural mandis, and local wholesalers", nearby: ["raipur", "dhamtari", "gariaband", "baloda-bazar-bhatapara"] },
  { name: "Balod", slug: "balod", state: "Chhattisgarh", type: "district", tagline: "a rice-growing district carved out of Durg in central Chhattisgarh", context: "the rice-mill trade, agricultural mandis, and local retail", nearby: ["durg", "rajnandgaon", "bemetara", "dhamtari"] },
  { name: "Bemetara", slug: "bemetara", state: "Chhattisgarh", type: "district", tagline: "a rice-mandi district carved out of Durg, part of Chhattisgarh's paddy belt", context: "the rice-mill trade, agricultural markets, and local wholesalers", nearby: ["durg", "balod", "raipur", "rajnandgaon"] },
  { name: "Kabirdham", slug: "kabirdham", state: "Chhattisgarh", type: "growing", tagline: "the district headquartered at Kawardha, on the edge of the Maikal hills", context: "the rice-mill trade, forest-produce businesses, and agricultural markets", nearby: ["bilaspur", "rajnandgaon", "durg", "bemetara"] },
  { name: "Rajnandgaon", slug: "rajnandgaon", state: "Chhattisgarh", type: "headquarters", tagline: "a former princely-state capital and textile-and-rice trading town west of Durg", context: "the textile weaving units, rice-mill trade, and agricultural markets", nearby: ["durg", "bhilai", "kabirdham", "balod"] },
  { name: "Khairagarh-Chhuikhadan-Gandai", slug: "khairagarh-chhuikhadan-gandai", state: "Chhattisgarh", type: "district", tagline: "a newly carved district around Khairagarh, home to India's only music-and-fine-arts university", context: "the agricultural trade, education-linked economy, and local retail", nearby: ["rajnandgaon", "durg", "kabirdham", "bemetara"] },
  { name: "Mohla-Manpur-Ambagarh Chowki", slug: "mohla-manpur-ambagarh-chowki", state: "Chhattisgarh", type: "district", tagline: "a newly carved tribal district on Chhattisgarh's Maharashtra border, split out of Rajnandgaon", context: "the forest-produce trade, agricultural markets, and local retail", nearby: ["rajnandgaon", "khairagarh-chhuikhadan-gandai", "kabirdham", "durg"] },
  { name: "Gaurela-Pendra-Marwahi", slug: "gaurela-pendra-marwahi", state: "Chhattisgarh", type: "district", tagline: "a hill-plateau district carved out of Bilaspur, on the Chhattisgarh-MP forest border", context: "the forest-produce trade, agricultural markets, and local retail", nearby: ["bilaspur", "koriya", "anuppur", "shahdol"] },
  { name: "Janjgir-Champa", slug: "janjgir-champa", state: "Chhattisgarh", type: "growing", tagline: "a rice-and-thermal-power belt district headquarters on the Hasdeo river", context: "the rice-mill trade, power-plant ancillary units, and agricultural markets", nearby: ["bilaspur", "raigarh", "sakti", "korba"] },
  { name: "Sakti", slug: "sakti", state: "Chhattisgarh", type: "district", tagline: "a rice-mandi district newly carved out of Janjgir-Champa in eastern Chhattisgarh", context: "the rice-mill trade, agricultural markets, and local wholesalers", nearby: ["janjgir-champa", "bilaspur", "raigarh", "korba"] },
  { name: "Sarangarh-Bilaigarh", slug: "sarangarh-bilaigarh", state: "Chhattisgarh", type: "district", tagline: "a rice-and-forest district newly carved out of Raigarh in eastern Chhattisgarh", context: "the rice-mill trade, forest-produce businesses, and agricultural markets", nearby: ["raigarh", "janjgir-champa", "sakti", "bilaspur"] },
  { name: "Surguja", slug: "surguja", state: "Chhattisgarh", type: "headquarters", tagline: "the district headquartered at Ambikapur, at the heart of the tribal Surguja plateau", context: "the forest-produce trade, coal-mining ancillary units, and agricultural markets", nearby: ["koriya", "jashpur", "balrampur-ramanujganj", "surajpur"] },
  { name: "Koriya", slug: "koriya", state: "Chhattisgarh", type: "growing", tagline: "a coalfield district headquartered at Baikunthpur, on Chhattisgarh's northern plateau", context: "the coal-mining trade, power-ancillary units, and forest-produce businesses", nearby: ["surguja", "surajpur", "gaurela-pendra-marwahi", "manendragarh-chirmiri-bharatpur"] },
  { name: "Balrampur-Ramanujganj", slug: "balrampur-ramanujganj", state: "Chhattisgarh", type: "district", tagline: "a tribal plateau district on Chhattisgarh's border with Uttar Pradesh and Jharkhand", context: "the forest-produce trade, agricultural markets, and local retail", nearby: ["surguja", "surajpur", "jashpur", "sarguja"] },
  { name: "Surajpur", slug: "surajpur", state: "Chhattisgarh", type: "district", tagline: "a tribal-belt district carved out of Surguja on the Chhattisgarh plateau", context: "the agricultural trade, forest-produce businesses, and local markets", nearby: ["surguja", "balrampur-ramanujganj", "koriya", "jashpur"] },
  { name: "Manendragarh-Chirmiri-Bharatpur", slug: "manendragarh-chirmiri-bharatpur", state: "Chhattisgarh", type: "district", tagline: "a coalfield district newly carved out of Koriya on Chhattisgarh's MP border", context: "the coal-mining trade, power-ancillary units, and forest-produce businesses", nearby: ["koriya", "surguja", "gaurela-pendra-marwahi", "singrauli"] },
  { name: "Bastar", slug: "bastar", state: "Chhattisgarh", type: "headquarters", tagline: "the district headquartered at Jagdalpur, at the heart of the tribal Bastar plateau and its Chitrakote waterfalls", context: "the forest-produce and Bastar handicraft trade, tribal cooperative businesses, and tourism", nearby: ["kondagaon", "dantewada", "narayanpur", "north-bastar-kanker"] },
  { name: "Kondagaon", slug: "kondagaon", state: "Chhattisgarh", type: "growing", tagline: "a Bastar-region district renowned for its bell-metal and wood-carving tribal art", context: "the tribal handicraft export trade, forest-produce businesses, and agricultural markets", nearby: ["bastar", "narayanpur", "north-bastar-kanker", "dhamtari"] },
  { name: "Narayanpur", slug: "narayanpur", state: "Chhattisgarh", type: "district", tagline: "a remote tribal district in the Abujhmarh hills of the Bastar plateau", context: "the forest-produce trade, tribal cooperative businesses, and local markets", nearby: ["kondagaon", "bastar", "bijapur", "north-bastar-kanker"] },
  { name: "North Bastar Kanker", slug: "north-bastar-kanker", state: "Chhattisgarh", type: "growing", tagline: "the northern gateway district of the Bastar plateau, headquartered at Kanker", context: "the forest-produce trade, agricultural markets, and tribal cooperative businesses", nearby: ["kondagaon", "bastar", "dhamtari", "raipur"] },
  { name: "Dantewada", slug: "dantewada", state: "Chhattisgarh", type: "growing", tagline: "a Bastar tribal district built on the Bailadila iron-ore mining belt", context: "the iron-ore mining trade, tribal cooperative businesses, and forest-produce markets", nearby: ["bastar", "sukma", "bijapur", "kondagaon"] },
  { name: "Sukma", slug: "sukma", state: "Chhattisgarh", type: "district", tagline: "a remote southern Bastar tribal district on Chhattisgarh's border with Andhra Pradesh and Odisha", context: "the forest-produce trade, tribal cooperative businesses, and agricultural markets", nearby: ["dantewada", "bijapur", "bastar", "narayanpur"] },
  { name: "Bijapur", slug: "bijapur", state: "Chhattisgarh", type: "district", tagline: "a remote, densely forested tribal district in the southern Bastar plateau", context: "the forest-produce trade, tribal cooperative businesses, and agricultural markets", nearby: ["dantewada", "sukma", "narayanpur", "bastar"] },
  { name: "Mungeli", slug: "mungeli", state: "Chhattisgarh", type: "district", tagline: "a rice-mandi district carved out of Bilaspur in central Chhattisgarh", context: "the rice-mill trade, agricultural markets, and local wholesalers", nearby: ["bilaspur", "kabirdham", "raipur", "durg"] },
  { name: "Jashpur", slug: "jashpur", state: "Chhattisgarh", type: "growing", tagline: "a hilly tribal district on Chhattisgarh's Jharkhand-Odisha border, known for small tea and coffee plantations", context: "the tea and horticulture trade, forest-produce businesses, and agricultural markets", nearby: ["surguja", "raigarh", "balrampur-ramanujganj", "koriya"] },

  // ═══════════ DADRA & NAGAR HAVELI AND DAMAN & DIU ═══════════
  { name: "Diu", slug: "diu", state: "Dadra & Nagar Haveli and Daman & Diu", type: "growing", tagline: "a former Portuguese island territory off the Gujarat coast, a separate island from Daman across the sea", context: "the tourism and hospitality trade, fisheries, and duty-free retail", nearby: ["daman", "silvassa", "junagadh", "bhavnagar"] },
];
