import type { CityInfo } from "@/lib/localSeo";

/* GAP-FILL BATCH — real Maharashtra + Gujarat district headquarters not yet
   covered by maharashtraCities / gujaratCities in lib/localSeo.ts. Sourced
   against lib/geo.ts's district list; "Devbhoomi Dwarka" (alternate spelling
   of "Devbhumi Dwarka") was dropped here — same real place, two spellings in
   the source data, keeping both would be a duplicate-content page. */
export const group6Cities: CityInfo[] = [
  // ── MAHARASHTRA ──────────────────────────────────────────────
  { name: "Palghar", slug: "palghar", state: "Maharashtra", type: "growing", tagline: "an industrial and coastal district split from Thane, anchoring Mumbai's northern MIDC belt", context: "the Tarapur and Boisar industrial estates, Vasai-Virar retail growth, and fishing communities", nearby: ["mumbai", "thane", "nashik", "raigad"] },
  { name: "Raigad", slug: "raigad", state: "Maharashtra", type: "growing", tagline: "a Konkan coastal district south of Mumbai with chemical estates and Alphonso mango orchards", context: "the JNPT-linked logistics and chemical units, Alibaug tourism trade, and mango and fishing exporters", nearby: ["mumbai", "navi-mumbai", "pune", "ratnagiri"] },
  { name: "Ratnagiri", slug: "ratnagiri", state: "Maharashtra", type: "headquarters", tagline: "the Konkan coast's Alphonso mango and cashew capital", context: "the mango and cashew export trade, fishing harbours, and Konkan Railway-linked logistics", nearby: ["sindhudurg", "raigad", "mumbai", "pune"] },
  { name: "Sindhudurg", slug: "sindhudurg", state: "Maharashtra", type: "growing", tagline: "Maharashtra's southernmost coastal district, built on beach tourism and kokum-cashew trade", context: "the coastal tourism and homestay trade, cashew and kokum processing, and fishing businesses", nearby: ["ratnagiri", "raigad", "mumbai", "pune"] },
  { name: "Dhule", slug: "dhule", state: "Maharashtra", type: "headquarters", tagline: "a Khandesh trading town on the Mumbai-Agra highway with a strong cotton mandi", context: "the cotton and agricultural trade, transport logistics, and local wholesalers", nearby: ["jalgaon", "nandurbar", "nashik", "aurangabad"] },
  { name: "Nandurbar", slug: "nandurbar", state: "Maharashtra", type: "district", tagline: "a tribal-majority Khandesh district bordering Madhya Pradesh and Gujarat", context: "the chilli and cotton trade, agricultural markets, and local retail businesses", nearby: ["dhule", "jalgaon", "nashik", "surat"] },
  { name: "Jalgaon", slug: "jalgaon", state: "Maharashtra", type: "headquarters", tagline: "the Banana City of India and a gold-jewellery trading hub of Khandesh", context: "the banana cultivation and trade, gold and jewellery businesses, and cotton mandis", nearby: ["dhule", "nandurbar", "nashik", "aurangabad"] },
  { name: "Ahilyanagar", slug: "ahilyanagar", state: "Maharashtra", type: "headquarters", tagline: "the sugar-cooperative heartland of western Maharashtra, formerly Ahmednagar", context: "the sugar cooperatives, pomegranate and grape orchards, and defence-linked institutions", nearby: ["pune", "nashik", "aurangabad", "solapur"] },
  { name: "Satara", slug: "satara", state: "Maharashtra", type: "headquarters", tagline: "a hill-station gateway and sugar-belt district on the Pune-Kolhapur corridor", context: "the sugar cooperatives, education institutions, and hill-tourism businesses", nearby: ["pune", "kolhapur", "sangli", "solapur"] },
  { name: "Sangli", slug: "sangli", state: "Maharashtra", type: "headquarters", tagline: "home to one of Asia's largest turmeric markets and a grape-and-raisin belt", context: "the turmeric trading market, grape and raisin processing, and sugar cooperatives", nearby: ["kolhapur", "satara", "solapur", "pune"] },
  { name: "Jalna", slug: "jalna", state: "Maharashtra", type: "growing", tagline: "a Marathwada industrial town known for seedless grapes and steel bearings", context: "the steel and bearing manufacturing units, seedless-grape exporters, and MIDC industries", nearby: ["aurangabad", "parbhani", "beed", "nanded"] },
  { name: "Beed", slug: "beed", state: "Maharashtra", type: "district", tagline: "a Marathwada agricultural district built on sugarcane and cotton trade", context: "the sugarcane and cotton mandis, agricultural markets, and local retail businesses", nearby: ["jalna", "aurangabad", "latur", "ahilyanagar"] },
  { name: "Dharashiv", slug: "dharashiv", state: "Maharashtra", type: "district", tagline: "a drought-prone Marathwada district, formerly Osmanabad, anchored by sugarcane trade", context: "the sugarcane and cotton mandis, agricultural cooperatives, and local wholesalers", nearby: ["latur", "beed", "solapur", "nanded"] },
  { name: "Parbhani", slug: "parbhani", state: "Maharashtra", type: "headquarters", tagline: "a Marathwada agricultural-research town centred on the region's soybean and cotton trade", context: "the agricultural university-linked economy, soybean and cotton mandis, and local retail", nearby: ["jalna", "nanded", "hingoli", "latur"] },
  { name: "Latur", slug: "latur", state: "Maharashtra", type: "headquarters", tagline: "Marathwada's major pulses-trading hub and a nationally known coaching-education town", context: "the dal and pulses trading mandis, coaching-institute economy, and agricultural markets", nearby: ["nanded", "beed", "dharashiv", "parbhani"] },
  { name: "Nanded", slug: "nanded", state: "Maharashtra", type: "headquarters", tagline: "a Sikh pilgrimage city built around the Hazur Sahib Gurudwara, with a growing textile trade", context: "the pilgrimage tourism trade, textile and agricultural markets, and local wholesalers", nearby: ["latur", "parbhani", "hingoli", "jalna"] },
  { name: "Hingoli", slug: "hingoli", state: "Maharashtra", type: "district", tagline: "Marathwada's smallest district, an agrarian turmeric-and-grain trading town", context: "the turmeric and grain mandis, agricultural cooperatives, and local retail businesses", nearby: ["parbhani", "nanded", "akola", "washim"] },
  { name: "Akola", slug: "akola", state: "Maharashtra", type: "headquarters", tagline: "a Vidarbha cotton-trading hub built around its agricultural university", context: "the cotton mandis, agricultural research institutions, and local wholesalers", nearby: ["buldhana", "washim", "amravati", "yavatmal"] },
  { name: "Buldhana", slug: "buldhana", state: "Maharashtra", type: "district", tagline: "a Vidarbha cotton-and-soybean belt district near the Lonar crater lake", context: "the cotton and soybean mandis, agricultural trade, and tourism around Lonar lake", nearby: ["akola", "washim", "jalgaon", "amravati"] },
  { name: "Washim", slug: "washim", state: "Maharashtra", type: "district", tagline: "a smaller Vidarbha agrarian district built on cotton and soybean trade", context: "the cotton and soybean mandis, agricultural markets, and local retail businesses", nearby: ["akola", "buldhana", "hingoli", "yavatmal"] },
  { name: "Yavatmal", slug: "yavatmal", state: "Maharashtra", type: "district", tagline: "a major Vidarbha cotton-trading district with an active agricultural mandi economy", context: "the cotton mandis, agricultural trade, and local wholesalers", nearby: ["akola", "washim", "wardha", "nanded"] },
  { name: "Wardha", slug: "wardha", state: "Maharashtra", type: "growing", tagline: "the Gandhian heritage town of Sevagram, growing on the back of MIHAN-linked logistics", context: "the textile and cotton trade, logistics growth near MIHAN, and heritage tourism", nearby: ["nagpur", "yavatmal", "chandrapur", "amravati"] },
  { name: "Bhandara", slug: "bhandara", state: "Maharashtra", type: "district", tagline: "an eastern Vidarbha rice-bowl district known for traditional brass utensil manufacturing", context: "the rice trade, brass utensil manufacturing, and agricultural markets", nearby: ["nagpur", "gondia", "chandrapur", "wardha"] },
  { name: "Gondia", slug: "gondia", state: "Maharashtra", type: "district", tagline: "an eastern Vidarbha rice-and-timber trading district bordering Madhya Pradesh and Chhattisgarh", context: "the rice mills, timber trade, and cross-border logistics firms", nearby: ["bhandara", "nagpur", "chandrapur", "raipur"] },
  { name: "Chandrapur", slug: "chandrapur", state: "Maharashtra", type: "headquarters", tagline: "a coal-and-power industrial hub of Vidarbha, gateway to the Tadoba tiger reserve", context: "the coal mining and thermal-power ancillary units, cement and paper industries, and wildlife tourism", nearby: ["nagpur", "gadchiroli", "wardha", "yavatmal"] },
  { name: "Gadchiroli", slug: "gadchiroli", state: "Maharashtra", type: "district", tagline: "a densely forested tribal Vidarbha district bordering Chhattisgarh and Telangana", context: "the forest-produce trade, mining-linked development, and local retail businesses", nearby: ["chandrapur", "gondia", "nagpur", "bhandara"] },

  // ── GUJARAT ──────────────────────────────────────────────────
  { name: "Kheda", slug: "kheda", state: "Gujarat", type: "headquarters", tagline: "a Charotar-region district long linked to Gujarat's dairy-cooperative movement", context: "the dairy cooperative economy, tobacco and agricultural trade, and local wholesalers", nearby: ["anand", "ahmedabad", "vadodara", "gandhinagar"] },
  { name: "Anand", slug: "anand", state: "Gujarat", type: "headquarters", tagline: "the Milk Capital of India, home to the Amul dairy-cooperative movement", context: "the dairy cooperative and processing industry, tobacco trade, and education institutions", nearby: ["kheda", "vadodara", "ahmedabad", "mehsana"] },
  { name: "Mahisagar", slug: "mahisagar", state: "Gujarat", type: "district", tagline: "a newer tribal district carved from Panchmahal, built on agriculture", context: "the agricultural markets, local retail businesses, and small-scale trade", nearby: ["panchmahal", "dahod", "kheda", "vadodara"] },
  { name: "Chhota Udaipur", slug: "chhota-udaipur", state: "Gujarat", type: "district", tagline: "a tribal district bordering Madhya Pradesh with bauxite mining and forest produce", context: "the bauxite mining trade, forest-produce businesses, and agricultural markets", nearby: ["vadodara", "narmada", "panchmahal", "dahod"] },
  { name: "Panchmahal", slug: "panchmahal", state: "Gujarat", type: "headquarters", tagline: "a central Gujarat trading district headquartered at Godhra on the Vadodara corridor", context: "the agricultural trade, transport logistics, and local wholesalers", nearby: ["vadodara", "dahod", "mahisagar", "kheda"] },
  { name: "Dahod", slug: "dahod", state: "Gujarat", type: "district", tagline: "an eastern tribal district bordering Madhya Pradesh, home to a major railway workshop", context: "the railway ancillary trade, maize and agricultural markets, and local retailers", nearby: ["panchmahal", "mahisagar", "vadodara", "chhota-udaipur"] },
  { name: "Tapi", slug: "tapi", state: "Gujarat", type: "district", tagline: "a tribal district carved from Surat, forested and agrarian", context: "the teak and forest-produce trade, agricultural markets, and local retail", nearby: ["surat", "narmada", "navsari", "vadodara"] },
  { name: "Bharuch", slug: "bharuch", state: "Gujarat", type: "headquarters", tagline: "a Narmada-riverside petrochemical hub anchored by the Dahej and Ankleshwar industrial estates", context: "the petrochemical and chemical manufacturing units, port-linked logistics, and industrial suppliers", nearby: ["surat", "vadodara", "narmada", "valsad"] },
  { name: "Narmada", slug: "narmada", state: "Gujarat", type: "growing", tagline: "the district around the Statue of Unity and Kevadia, driven by fast-growing tourism", context: "the dam and tourism-linked hospitality trade, tribal agriculture, and local retail", nearby: ["bharuch", "vadodara", "chhota-udaipur", "surat"] },
  { name: "Morbi", slug: "morbi", state: "Gujarat", type: "headquarters", tagline: "India's ceramic-tile manufacturing capital, also known for clock manufacturing", context: "the ceramic tile and sanitaryware industries, clock manufacturing units, and export trade", nearby: ["rajkot", "surendranagar", "jamnagar", "ahmedabad"] },
  { name: "Devbhumi Dwarka", slug: "devbhumi-dwarka", state: "Gujarat", type: "headquarters", tagline: "a Saurashtra coastal district anchored by the Dwarka pilgrimage temple", context: "the pilgrimage tourism trade, fishing and salt production, and local retail", nearby: ["jamnagar", "porbandar", "rajkot", "junagadh"] },
  { name: "Porbandar", slug: "porbandar", state: "Gujarat", type: "headquarters", tagline: "Mahatma Gandhi's birthplace, a fishing-harbour and cement-industry coastal town", context: "the fishing harbour trade, cement manufacturing, and coastal tourism", nearby: ["junagadh", "jamnagar", "rajkot", "devbhumi-dwarka"] },
  { name: "Botad", slug: "botad", state: "Gujarat", type: "district", tagline: "a newer Saurashtra district built on cotton and groundnut trade", context: "the cotton and groundnut mandis, diamond-polishing linkages, and local retail", nearby: ["bhavnagar", "rajkot", "surendranagar", "ahmedabad"] },
  { name: "Amreli", slug: "amreli", state: "Gujarat", type: "district", tagline: "a Saurashtra agricultural district trading in cotton and groundnut", context: "the cotton and groundnut trade, agricultural markets, and local wholesalers", nearby: ["bhavnagar", "junagadh", "rajkot", "botad"] },
  { name: "Gir Somnath", slug: "gir-somnath", state: "Gujarat", type: "growing", tagline: "home to the Somnath temple and the Gir forest lion sanctuary, driven by pilgrimage and wildlife tourism", context: "the pilgrimage and wildlife-tourism trade, fishing businesses, and local hospitality", nearby: ["junagadh", "amreli", "porbandar", "rajkot"] },
  { name: "Kutch", slug: "kutch", state: "Gujarat", type: "headquarters", tagline: "India's largest district by area, known for Kutchi embroidery, salt production, and post-earthquake industrial growth", context: "the handicraft and embroidery export trade, salt production, and industrial estates around Bhuj", nearby: ["jamnagar", "rajkot", "surendranagar", "ahmedabad"] },
  { name: "Mehsana", slug: "mehsana", state: "Gujarat", type: "headquarters", tagline: "a North Gujarat dairy-cooperative and oil-and-gas-field district", context: "the dairy cooperative economy, oil-and-gas ancillary trade, and diamond-cutting linkages", nearby: ["ahmedabad", "patan", "banaskantha", "gandhinagar"] },
  { name: "Patan", slug: "patan", state: "Gujarat", type: "growing", tagline: "a heritage North Gujarat town famed for the Rani ki Vav stepwell and Patola silk weaving", context: "the Patola silk weaving trade, heritage tourism, and agricultural markets", nearby: ["mehsana", "banaskantha", "ahmedabad", "surendranagar"] },
  { name: "Banaskantha", slug: "banaskantha", state: "Gujarat", type: "headquarters", tagline: "Gujarat's largest district by area, a Palanpur-headquartered agricultural and diamond-trade belt bordering Rajasthan", context: "the potato and castor agricultural trade, diamond-trade linkages, and dairy cooperatives", nearby: ["mehsana", "patan", "sabarkantha", "ahmedabad"] },
  { name: "Sabarkantha", slug: "sabarkantha", state: "Gujarat", type: "district", tagline: "a North Gujarat district headquartered at Himmatnagar, built on agriculture and dairy", context: "the dairy cooperative economy, agricultural markets, and local wholesalers", nearby: ["banaskantha", "aravalli", "mehsana", "gandhinagar"] },
  { name: "Aravalli", slug: "aravalli", state: "Gujarat", type: "district", tagline: "a newer North Gujarat district carved from Sabarkantha, agricultural and mineral-rich", context: "the agricultural trade, marble and mineral businesses, and local retail", nearby: ["sabarkantha", "banaskantha", "mehsana", "ahmedabad"] },
  { name: "Valsad", slug: "valsad", state: "Gujarat", type: "headquarters", tagline: "a South Gujarat industrial district neighbouring the Vapi chemical belt, also known for mango and chikoo orchards", context: "the chemical and industrial estates, mango and chikoo orchards, and fishing businesses", nearby: ["navsari", "surat", "bharuch", "dang"] },
  { name: "Navsari", slug: "navsari", state: "Gujarat", type: "growing", tagline: "a South Gujarat sugar-and-agriculture town with a strong Parsi heritage", context: "the sugar and agricultural trade, small industrial pockets, and local retail", nearby: ["surat", "valsad", "tapi", "dang"] },
  { name: "Dang", slug: "dang", state: "Gujarat", type: "district", tagline: "Gujarat's smallest and most forested district, home to the Saputara hill station", context: "the forest-produce and teak trade, hill-tourism businesses, and local retail", nearby: ["navsari", "tapi", "valsad", "surat"] },
  { name: "Surendranagar", slug: "surendranagar", state: "Gujarat", type: "district", tagline: "a Saurashtra cotton-ginning and salt-production district bordering the Little Rann of Kutch", context: "the cotton ginning mills, salt production, and agricultural trade", nearby: ["rajkot", "ahmedabad", "botad", "morbi"] }
];
