import type { RowEntry } from "./screens";

/*
  The screens that exist because every industry card gets its own phone.

  screens.ts was written when the section showed five phones per category; once
  each of the 55 cards in IndustriesSection needed one of its own, seventeen
  trades had no screen. They live here rather than being spliced into that file
  so the original eight category groups stay readable.

  Same rules as screens.ts: the masthead names a trade, never an invented
  business, and figures are illustrative of the trade rather than quotes. Every
  tab or filter carries at least three entries so no group renders half empty.
*/

export const extraScreens: RowEntry[] = [
  {
    id: "ecommerce",
    category: "Business & Retail",
    industry: "E-commerce & Retail",
    kicker: "Online store",
    headline: "A storefront",
    headlineAccent: "that ships.",
    blurb: "Catalogue, cart and courier in one place, without a marketplace taking a cut.",
    accent: "#f43f5e",
    theme: "midnight",
    archetype: "storefront",
    tabs: ["Trending", "Apparel", "Home"],
    items: [
      { n: "Cotton bedsheet set", meta: "Double · 2 pillow covers", price: 899, unit: "set", tab: "Trending" },
      { n: "Steel water bottle", meta: "1 litre · vacuum", price: 649, unit: "piece", tab: "Trending" },
      { n: "Bluetooth earbuds", meta: "30 hr backup · case", price: 1299, unit: "pair", tab: "Trending" },
      { n: "Round-neck T-shirt", meta: "Combed cotton · 6 colours", price: 449, unit: "piece", tab: "Apparel" },
      { n: "Denim jeans", meta: "Slim fit · 28–38", price: 1199, unit: "piece", tab: "Apparel" },
      { n: "Kurta, printed", meta: "Rayon · S–XXL", price: 799, unit: "piece", tab: "Apparel" },
      { n: "Storage baskets", meta: "Set of 3 · foldable", price: 549, unit: "set", tab: "Home" },
      { n: "Wall clock", meta: "12 inch · silent sweep", price: 699, unit: "piece", tab: "Home" },
      { n: "Kitchen organiser", meta: "Steel · 2 tier", price: 1099, unit: "piece", tab: "Home" },
    ],
    stats: [
      { to: 0, suffix: "%", label: "Marketplace cut" },
      { to: 3, suffix: " day", label: "Dispatch" },
      { to: 7, suffix: " day", label: "Returns" },
    ],
    cta: "Checkout",
  },
  {
    id: "franchise",
    category: "Business & Retail",
    industry: "Franchise Businesses",
    kicker: "Multi-outlet operations",
    headline: "Every outlet,",
    headlineAccent: "on one standard.",
    blurb: "Sales, stock and audit scores per branch, so a weak outlet shows up in a day.",
    accent: "#eab308",
    theme: "midnight",
    archetype: "portal",
    filters: ["Performance", "Stock", "Audit"],
    rows: [
      { code: "OUT-01", title: "Main Road branch", meta: "Month to date · 118% of target", status: "Ahead", filter: "Performance" },
      { code: "OUT-04", title: "Mall kiosk", meta: "Month to date · 74% of target", status: "Behind", filter: "Performance" },
      { code: "OUT-07", title: "Highway outlet", meta: "Month to date · 101% of target", status: "On track", filter: "Performance" },
      { code: "OUT-02", title: "Station branch", meta: "6 SKUs below reorder level", status: "Indent raised", filter: "Stock" },
      { code: "OUT-05", title: "Colony branch", meta: "Full stock · next drop Friday", status: "Healthy", filter: "Stock" },
      { code: "OUT-03", title: "Bypass branch", meta: "2 fast movers out", status: "Urgent", filter: "Stock" },
      { code: "AU-19", title: "Hygiene & uniform", meta: "Checked 12th · 9 of 10", status: "Pass", filter: "Audit" },
      { code: "AU-20", title: "Billing compliance", meta: "Checked 12th · 3 gaps", status: "Re-audit", filter: "Audit" },
      { code: "AU-21", title: "Signage & display", meta: "Checked 10th · brand kit current", status: "Pass", filter: "Audit" },
    ],
    stats: [
      { to: 12, label: "Outlets" },
      { to: 1, suffix: " day", label: "Reporting lag" },
      { to: 94, suffix: "%", label: "Audit pass" },
    ],
    cta: "Open outlet board",
  },
  {
    id: "corporate",
    category: "Professional",
    industry: "Corporate & Offices",
    kicker: "Workplace & admin",
    headline: "The office,",
    headlineAccent: "run from a phone.",
    blurb: "Desks, visitors and facility tickets stop living in three separate registers.",
    accent: "#334155",
    theme: "bright",
    archetype: "portal",
    filters: ["Today", "Visitors", "Facilities"],
    rows: [
      { code: "MTG-3", title: "Board room · 11:00–12:30", meta: "Quarterly review · 9 attendees", status: "Confirmed", filter: "Today" },
      { code: "MTG-7", title: "Huddle room · 3:00–3:30", meta: "Design sync · 4 attendees", status: "Confirmed", filter: "Today" },
      { code: "DSK-22", title: "Hot desk · Level 2", meta: "Assigned for the day", status: "Checked in", filter: "Today" },
      { code: "VIS-41", title: "Vendor · 10:40 am", meta: "Host notified · pass printed", status: "Inside", filter: "Visitors" },
      { code: "VIS-42", title: "Candidate · 2:15 pm", meta: "Interview panel · Level 3", status: "Expected", filter: "Visitors" },
      { code: "VIS-39", title: "Courier · 9:05 am", meta: "Handed at reception", status: "Closed", filter: "Visitors" },
      { code: "FM-88", title: "AC not cooling · Level 2", meta: "Raised 8:40 am", status: "Assigned", filter: "Facilities" },
      { code: "FM-86", title: "Printer jam · Level 1", meta: "Vendor called", status: "In progress", filter: "Facilities" },
      { code: "FM-81", title: "Pantry supplies", meta: "Weekly indent", status: "Delivered", filter: "Facilities" },
    ],
    stats: [
      { to: 240, label: "Seats" },
      { to: 4, suffix: " hr", label: "Ticket SLA" },
      { to: 0, label: "Paper registers" },
    ],
    cta: "Book a room",
  },
  {
    id: "taxconsultant",
    category: "Professional",
    industry: "Tax Consultants",
    kicker: "GST & income tax",
    headline: "Filings tracked",
    headlineAccent: "to the due date.",
    blurb: "Each client's returns, notices and refunds in one list instead of a WhatsApp trail.",
    accent: "#16a34a",
    theme: "glass",
    archetype: "portal",
    filters: ["Due", "Notices", "Refunds"],
    rows: [
      { code: "GST-3B", title: "Trader · monthly", meta: "Due 20th · 4 days left", status: "Data received", filter: "Due" },
      { code: "ITR-1", title: "Salaried · AY 25-26", meta: "Form 16 uploaded", status: "Computing", filter: "Due" },
      { code: "ADV-TAX", title: "Professional · Q3", meta: "Due 15th · estimate ready", status: "Awaiting approval", filter: "Due" },
      { code: "SEC-139(9)", title: "Defective return notice", meta: "Response due in 12 days", status: "Drafting", filter: "Notices" },
      { code: "GST-ASMT", title: "Scrutiny of returns", meta: "Reconciliation attached", status: "Replied", filter: "Notices" },
      { code: "SEC-143(1)", title: "Intimation received", meta: "Matches computation", status: "No action", filter: "Notices" },
      { code: "RF-2231", title: "Income tax refund", meta: "AY 24-25 · credited", status: "₹18,400", filter: "Refunds" },
      { code: "RF-2240", title: "GST refund, exports", meta: "ARN generated", status: "Processing", filter: "Refunds" },
      { code: "RF-2244", title: "TDS excess deducted", meta: "Claimed in return", status: "Awaited", filter: "Refunds" },
    ],
    stats: [
      { to: 320, suffix: "+", label: "Filings a year" },
      { to: 0, label: "Late fees" },
      { to: 24, suffix: " hr", label: "Query reply" },
    ],
    cta: "Track my filing",
  },
  {
    id: "coworking",
    category: "Professional",
    industry: "Co-working Spaces",
    kicker: "Desks & cabins",
    headline: "A desk held",
    headlineAccent: "before you arrive.",
    blurb: "Seat type and duration chosen up front, so nobody turns up to a full floor.",
    accent: "#8b5cf6",
    theme: "bright",
    archetype: "booking",
    services: [
      { n: "Hot desk", meta: "Any open seat · wifi + coffee", price: "₹300 /day" },
      { n: "Dedicated desk", meta: "Your own seat + locker", price: "₹5,500 /mo" },
      { n: "Private cabin", meta: "Seats 4 · lockable", price: "₹22,000 /mo" },
    ],
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    slots: ["Full day", "9–1", "1–5", "5–9", "Week", "Month"],
    stats: [
      { to: 120, label: "Seats" },
      { to: 6, label: "Meeting rooms" },
      { to: 24, suffix: "x7", label: "Access" },
    ],
    cta: "Reserve desk",
  },
  {
    id: "ngo",
    category: "Professional",
    industry: "NGOs & Trusts",
    kicker: "Programmes & giving",
    headline: "Where the money",
    headlineAccent: "actually went.",
    blurb: "Programmes, reach and spend published, because donors give again to what they can see.",
    accent: "#0d9488",
    theme: "paper",
    archetype: "studio",
    tabs: ["Education", "Health", "Livelihood"],
    works: [
      { title: "After-school centres", meta: "6 centres · 480 children · daily", tab: "Education" },
      { title: "Scholarship fund", meta: "Class 9–12 · 74 students", tab: "Education" },
      { title: "Library & reading", meta: "2,100 books · 3 villages", tab: "Education" },
      { title: "Health camps", meta: "Quarterly · free screening", tab: "Health" },
      { title: "Maternal nutrition", meta: "220 mothers · monthly kit", tab: "Health" },
      { title: "Eye check & spectacles", meta: "1,400 screened last year", tab: "Health" },
      { title: "Tailoring training", meta: "3 month course · 90 women", tab: "Livelihood" },
      { title: "Self-help groups", meta: "18 groups · savings linked", tab: "Livelihood" },
      { title: "Farm input support", meta: "140 small holders", tab: "Livelihood" },
    ],
    stats: [
      { to: 12, suffix: " yr", label: "Working since" },
      { to: 80, suffix: "%", label: "To programmes" },
      { to: 100, suffix: "%", label: "80G receipts" },
    ],
    cta: "Support a programme",
  },
  {
    id: "banking",
    category: "Professional",
    industry: "Banking & Finance",
    kicker: "Loans & advisory",
    headline: "An application",
    headlineAccent: "you can follow.",
    blurb: "Every file's stage and what it is waiting on, instead of a fortnight of silence.",
    accent: "#1d4ed8",
    theme: "midnight",
    archetype: "portal",
    filters: ["In process", "Sanctioned", "Documents"],
    rows: [
      { code: "HL-1182", title: "Home loan · ₹28 L", meta: "Legal & valuation done", status: "Credit review", filter: "In process" },
      { code: "BL-0447", title: "Business loan · ₹12 L", meta: "GST returns verified", status: "Underwriting", filter: "In process" },
      { code: "VL-2210", title: "Vehicle loan · ₹8 L", meta: "Dealer quote received", status: "Field check", filter: "In process" },
      { code: "HL-1160", title: "Home loan · ₹35 L", meta: "Sanction letter issued", status: "Disbursal due", filter: "Sanctioned" },
      { code: "LAP-0312", title: "Loan against property", meta: "₹40 L · 9.4% floating", status: "Agreement", filter: "Sanctioned" },
      { code: "BL-0431", title: "Working capital · ₹6 L", meta: "Limit set up", status: "Active", filter: "Sanctioned" },
      { code: "KYC", title: "PAN & Aadhaar", meta: "Verified digitally", status: "Complete", filter: "Documents" },
      { code: "ITR", title: "Returns, 2 years", meta: "Uploaded 11th", status: "Complete", filter: "Documents" },
      { code: "BANK", title: "Statements, 6 months", meta: "One account pending", status: "Awaited", filter: "Documents" },
    ],
    stats: [
      { to: 7, suffix: " day", label: "Sanction" },
      { to: 4, label: "Stages tracked" },
      { to: 0, label: "Branch visits" },
    ],
    cta: "Check eligibility",
  },
  {
    id: "automobile",
    category: "Home & Local",
    industry: "Automobile & Services",
    kicker: "Sales & service",
    headline: "Service booked",
    headlineAccent: "before the noise gets worse.",
    blurb: "Job type, pickup and a slot chosen in the app — the bay is ready when the car arrives.",
    accent: "#ef4444",
    theme: "midnight",
    archetype: "booking",
    services: [
      { n: "Periodic service", meta: "Oil, filters, 22-point check", price: "₹3,400" },
      { n: "Brake & suspension", meta: "Pads, discs, inspection", price: "₹5,200" },
      { n: "AC service", meta: "Gas top-up · cabin filter", price: "₹2,600" },
    ],
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    slots: ["8:30", "10:00", "11:30", "1:00", "2:30", "4:00"],
    stats: [
      { to: 8, label: "Service bays" },
      { to: 6, suffix: " hr", label: "Same-day" },
      { to: 100, suffix: "%", label: "Genuine parts" },
    ],
    cta: "Book service",
  },
  {
    id: "homedecor",
    category: "Home & Local",
    industry: "Home Decor",
    kicker: "Furnishing & styling",
    headline: "A room, priced",
    headlineAccent: "piece by piece.",
    blurb: "Everything in the frame listed with its price, so a look is something you can actually buy.",
    accent: "#b45309",
    theme: "paper",
    archetype: "catalog",
    filters: ["Lighting", "Soft furnishing", "Wall & floor"],
    listings: [
      { title: "Pendant light, brass", meta: "Single drop · warm white", price: "₹3,200", tag: "In stock", filter: "Lighting" },
      { title: "Floor lamp, cane", meta: "Hand woven · 5 ft", price: "₹5,400", tag: "2 left", filter: "Lighting" },
      { title: "Wall sconce pair", meta: "Matte black · dimmable", price: "₹2,800", tag: "New in", filter: "Lighting" },
      { title: "Cotton curtains", meta: "Blackout lined · 9 ft · pair", price: "₹4,100", tag: "6 colours", filter: "Soft furnishing" },
      { title: "Cushion cover set", meta: "Block print · set of 5", price: "₹1,450", tag: "Bestseller", filter: "Soft furnishing" },
      { title: "Handloom throw", meta: "Wool blend · 50 x 70 in", price: "₹2,600", tag: "Limited", filter: "Soft furnishing" },
      { title: "Textured wall panel", meta: "MDF · per sq ft · fitted", price: "₹340", tag: "Site visit", filter: "Wall & floor" },
      { title: "Jute area rug", meta: "6 x 4 ft · hand braided", price: "₹4,900", tag: "In stock", filter: "Wall & floor" },
      { title: "Gallery frame set", meta: "9 frames · layout guide", price: "₹2,200", tag: "Popular", filter: "Wall & floor" },
    ],
    stats: [
      { to: 400, suffix: "+", label: "Pieces" },
      { to: 5, suffix: " day", label: "Delivery" },
      { to: 3, label: "Style boards" },
    ],
    cta: "Book a styling call",
  },
  {
    id: "repairshop",
    category: "Home & Local",
    industry: "Repair Services",
    kicker: "Appliance & device repair",
    headline: "Drop it in,",
    headlineAccent: "follow it home.",
    blurb: "A job number the customer can check, so nobody rings the counter asking if it is ready.",
    accent: "#0284c7",
    theme: "glass",
    archetype: "portal",
    filters: ["Received", "In repair", "Ready"],
    rows: [
      { code: "JB-7741", title: "Washing machine · front load", meta: "Drain fault · booked 9:20 am", status: "Diagnosing", filter: "Received" },
      { code: "JB-7742", title: "Microwave oven", meta: "No heating · at counter", status: "Queued", filter: "Received" },
      { code: "JB-7739", title: "Laptop · screen", meta: "Panel ordered · 2 day wait", status: "Awaiting part", filter: "In repair" },
      { code: "JB-7735", title: "Refrigerator", meta: "Compressor replaced · testing", status: "Testing", filter: "In repair" },
      { code: "JB-7736", title: "Smartphone · charging port", meta: "Board level · reflow done", status: "In progress", filter: "In repair" },
      { code: "JB-7728", title: "Ceiling fan · winding", meta: "Tested 30 min · quiet", status: "Collect", filter: "Ready" },
      { code: "JB-7730", title: "Mixer grinder", meta: "Coupler + switch replaced", status: "Collect", filter: "Ready" },
      { code: "JB-7724", title: "LED television, 43 in", meta: "Backlight strip replaced", status: "Collect", filter: "Ready" },
      { code: "JB-7719", title: "Inverter battery", meta: "Terminals cleaned · load tested", status: "Collect", filter: "Ready" },
    ],
    stats: [
      { to: 48, suffix: " hr", label: "Typical turnaround" },
      { to: 90, suffix: " day", label: "Repair warranty" },
      { to: 0, label: "Follow-up calls" },
    ],
    cta: "Track job number",
  },
  {
    id: "idservices",
    category: "Home & Local",
    industry: "ID & Documentation",
    kicker: "Forms, cards & certificates",
    headline: "The queue,",
    headlineAccent: "moved online.",
    blurb: "Which document, what it needs, and where the application has actually reached.",
    accent: "#0f766e",
    theme: "bright",
    archetype: "portal",
    filters: ["Applied", "Verification", "Issued"],
    rows: [
      { code: "AP-4412", title: "PAN card, new", meta: "Form 49A · photo + sign uploaded", status: "Submitted", filter: "Applied" },
      { code: "AP-4415", title: "Voter ID correction", meta: "Name spelling · Form 8", status: "Submitted", filter: "Applied" },
      { code: "AP-4418", title: "Passport, fresh", meta: "Appointment booked 22nd", status: "Slot held", filter: "Applied" },
      { code: "AP-4401", title: "Income certificate", meta: "Block office · field enquiry", status: "Under check", filter: "Verification" },
      { code: "AP-4404", title: "Residence certificate", meta: "Documents matched", status: "Under check", filter: "Verification" },
      { code: "AP-4398", title: "Caste certificate", meta: "Awaiting officer sign", status: "Final stage", filter: "Verification" },
      { code: "AP-4380", title: "Aadhaar update", meta: "Address changed · e-Aadhaar", status: "Download", filter: "Issued" },
      { code: "AP-4376", title: "Driving licence renewal", meta: "Card dispatched", status: "In post", filter: "Issued" },
      { code: "AP-4371", title: "Birth certificate", meta: "Collected 9th", status: "Handed over", filter: "Issued" },
    ],
    stats: [
      { to: 30, suffix: "+", label: "Document types" },
      { to: 0, label: "Repeat visits" },
      { to: 15, suffix: " day", label: "Typical issue" },
    ],
    cta: "Check application",
  },
  {
    id: "agriculture",
    category: "Industrial",
    industry: "Agriculture & Dairy",
    kicker: "Farm inputs & produce",
    headline: "Rates and inputs,",
    headlineAccent: "before the trip to town.",
    blurb: "Mandi prices and what is in stock, so a day is not lost finding out.",
    accent: "#65a30d",
    theme: "bright",
    archetype: "portal",
    filters: ["Mandi rates", "Inputs", "Collection"],
    rows: [
      { code: "WHEAT", title: "Wheat · mill quality", meta: "Local mandi · today", status: "₹2,410 /qtl", filter: "Mandi rates" },
      { code: "PADDY", title: "Paddy · common", meta: "Local mandi · today", status: "₹2,180 /qtl", filter: "Mandi rates" },
      { code: "MAIZE", title: "Maize · dry", meta: "Local mandi · today", status: "₹1,960 /qtl", filter: "Mandi rates" },
      { code: "SEED", title: "Certified wheat seed", meta: "HD-2967 · 40 kg bag", status: "In stock", filter: "Inputs" },
      { code: "FERT", title: "Urea, 45 kg", meta: "Subsidised · Aadhaar required", status: "Limited", filter: "Inputs" },
      { code: "PEST", title: "Crop protection", meta: "Advisory before sale", status: "In stock", filter: "Inputs" },
      { code: "MILK-AM", title: "Morning collection", meta: "Fat 4.2 · SNF 8.4 · 12 L", status: "₹546", filter: "Collection" },
      { code: "MILK-PM", title: "Evening collection", meta: "Fat 4.0 · SNF 8.3 · 9 L", status: "₹389", filter: "Collection" },
      { code: "PAY", title: "Fortnight payment", meta: "Credited to bank", status: "₹8,240", filter: "Collection" },
    ],
    stats: [
      { to: 2, label: "Collections daily" },
      { to: 15, suffix: " day", label: "Payment cycle" },
      { to: 0, label: "Rate disputes" },
    ],
    cta: "See today's rate",
  },
  {
    id: "importexport",
    category: "Industrial",
    industry: "Import & Export",
    kicker: "Trade & documentation",
    headline: "Shipments and papers",
    headlineAccent: "in the same place.",
    blurb: "Containers, documents and payment terms tracked together, because they fail together.",
    accent: "#0ea5e9",
    theme: "glass",
    archetype: "portal",
    filters: ["Shipments", "Documents", "Payment"],
    rows: [
      { code: "SH-2291", title: "1 x 40 ft · to Jebel Ali", meta: "Gated in · vessel 18th", status: "At port", filter: "Shipments" },
      { code: "SH-2288", title: "2 x 20 ft · to Singapore", meta: "On water · ETA 26th", status: "In transit", filter: "Shipments" },
      { code: "SH-2280", title: "1 x 40 ft · from Shanghai", meta: "Customs cleared 11th", status: "Delivered", filter: "Shipments" },
      { code: "BL", title: "Bill of lading", meta: "Original couriered", status: "Issued", filter: "Documents" },
      { code: "COO", title: "Certificate of origin", meta: "Chamber attested", status: "Issued", filter: "Documents" },
      { code: "PHYTO", title: "Phytosanitary certificate", meta: "Inspection scheduled", status: "Pending", filter: "Documents" },
      { code: "LC-118", title: "Letter of credit", meta: "Confirmed · 60 day usance", status: "Open", filter: "Payment" },
      { code: "LC-114", title: "Documents negotiated", meta: "Bank accepted · no discrepancy", status: "Accepted", filter: "Payment" },
      { code: "RM-92", title: "Remittance received", meta: "FIRC issued", status: "Realised", filter: "Payment" },
    ],
    stats: [
      { to: 22, label: "Destinations" },
      { to: 60, suffix: " day", label: "Usance" },
      { to: 0, label: "Doc discrepancies" },
    ],
    cta: "Track shipment",
  },
  {
    id: "petcare",
    category: "Medical & Wellness",
    industry: "Pet Care & Veterinary",
    kicker: "Clinic & grooming",
    headline: "A slot for",
    headlineAccent: "the whole family.",
    blurb: "Vaccination due dates and grooming booked together, with the record kept per pet.",
    accent: "#f97316",
    theme: "bright",
    archetype: "booking",
    services: [
      { n: "Vet consultation", meta: "Exam · 20 min · records kept", price: "₹600" },
      { n: "Vaccination", meta: "Annual booster · certificate", price: "₹900" },
      { n: "Grooming & bath", meta: "Wash, trim, nails · 90 min", price: "₹1,200" },
    ],
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sun"],
    slots: ["10:00", "11:30", "1:00", "3:30", "5:00", "6:30"],
    stats: [
      { to: 2, label: "Vets on call" },
      { to: 12, suffix: " mo", label: "Booster reminder" },
      { to: 100, suffix: "%", label: "Records kept" },
    ],
    cta: "Book for my pet",
  },
  {
    id: "cosmetics",
    category: "Medical & Wellness",
    industry: "Cosmetics & Skincare",
    kicker: "Beauty retail",
    headline: "Shade matched",
    headlineAccent: "before it ships.",
    blurb: "Skin type and shade chosen in the app, which is most of why beauty gets returned.",
    accent: "#db2777",
    theme: "bright",
    archetype: "storefront",
    tabs: ["Skincare", "Makeup", "Hair"],
    items: [
      { n: "Vitamin C serum", meta: "20 ml · all skin types", price: 749, unit: "bottle", tab: "Skincare" },
      { n: "Sunscreen SPF 50", meta: "50 g · no white cast", price: 549, unit: "tube", tab: "Skincare" },
      { n: "Gel face wash", meta: "100 ml · oily skin", price: 349, unit: "tube", tab: "Skincare" },
      { n: "Liquid foundation", meta: "8 shades · matte finish", price: 899, unit: "bottle", tab: "Makeup" },
      { n: "Matte lipstick", meta: "12 shades · transfer proof", price: 499, unit: "piece", tab: "Makeup" },
      { n: "Kajal & liner set", meta: "Smudge proof · 2 piece", price: 399, unit: "set", tab: "Makeup" },
      { n: "Argan hair oil", meta: "100 ml · cold pressed", price: 649, unit: "bottle", tab: "Hair" },
      { n: "Anti-dandruff shampoo", meta: "200 ml · sulphate free", price: 579, unit: "bottle", tab: "Hair" },
      { n: "Hair mask", meta: "200 g · weekly treatment", price: 699, unit: "jar", tab: "Hair" },
    ],
    stats: [
      { to: 12, label: "Shades" },
      { to: 7, suffix: " day", label: "Returns" },
      { to: 100, suffix: "%", label: "Original" },
    ],
    cta: "Add to bag",
  },
  {
    id: "bookstore",
    category: "Education",
    industry: "Book Stores",
    kicker: "Books & stationery",
    headline: "The whole class list,",
    headlineAccent: "in one order.",
    blurb: "Set books by class and board, so a parent buys the year's list in a single trip.",
    accent: "#7c2d12",
    theme: "paper",
    archetype: "storefront",
    tabs: ["School sets", "Competitive", "Stationery"],
    items: [
      { n: "Class 8 full set", meta: "NCERT · all subjects", price: 1450, unit: "set", tab: "School sets" },
      { n: "Class 10 full set", meta: "NCERT + guides", price: 2380, unit: "set", tab: "School sets" },
      { n: "Class 12 science set", meta: "PCM · NCERT + reference", price: 3100, unit: "set", tab: "School sets" },
      { n: "SSC combined guide", meta: "Latest edition · solved papers", price: 680, unit: "book", tab: "Competitive" },
      { n: "Banking prelims set", meta: "3 books · practice sets", price: 1240, unit: "set", tab: "Competitive" },
      { n: "General knowledge annual", meta: "Current affairs · yearly", price: 420, unit: "book", tab: "Competitive" },
      { n: "Notebook bundle", meta: "10 x 200 pages · ruled", price: 560, unit: "bundle", tab: "Stationery" },
      { n: "Geometry box", meta: "Steel · full set", price: 240, unit: "box", tab: "Stationery" },
      { n: "Exam pad & pens", meta: "Clip board + 10 pens", price: 320, unit: "pack", tab: "Stationery" },
    ],
    stats: [
      { to: 5000, suffix: "+", label: "Titles" },
      { to: 3, label: "Boards covered" },
      { to: 1, suffix: " day", label: "Set ready" },
    ],
    cta: "Order class set",
  },
  {
    id: "digitalcreator",
    category: "Creative & Media",
    industry: "Digital Creators",
    kicker: "Content & community",
    headline: "A slate brands",
    headlineAccent: "can buy into.",
    blurb: "What is publishing, when, and where a sponsor would actually sit in it.",
    accent: "#f472b6",
    theme: "midnight",
    archetype: "studio",
    tabs: ["Long form", "Shorts", "Community"],
    works: [
      { title: "Weekly deep dive", meta: "12–15 min · Thursdays", tab: "Long form" },
      { title: "Interview series", meta: "Monthly guest · 30 min", tab: "Long form" },
      { title: "Explainer set", meta: "Evergreen · 8 min each", tab: "Long form" },
      { title: "Daily shorts", meta: "60 sec · 5 a week", tab: "Shorts" },
      { title: "Trend reactions", meta: "Same-day turnaround", tab: "Shorts" },
      { title: "Tutorial clips", meta: "Cut from long form", tab: "Shorts" },
      { title: "Members' Q&A", meta: "Live · fortnightly", tab: "Community" },
      { title: "Newsletter", meta: "Weekly · 9,400 subscribers", tab: "Community" },
      { title: "Discord & polls", meta: "Topic voting · 2,100 members", tab: "Community" },
    ],
    stats: [
      { to: 5, label: "Posts a week" },
      { to: 9.4, decimals: 1, suffix: "k", label: "Subscribers" },
      { to: 2, label: "Sponsor slots" },
    ],
    cta: "See the rate card",
  },
];
